//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McK.EIG.ROI.Client.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/securitylogoff")]
        public string McK_EIG_ROI_Client_Web_References_SecurityLogoffWS_SecurityLogoffService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_SecurityLogoffWS_SecurityLogoffService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/InUseService")]
        public string McK_EIG_ROI_Client_Web_References_InUseWS_InUseService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_InUseWS_InUseService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/patient")]
        public string McK_EIG_ROI_Client_Web_References_HPFPatientWS_PatientService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_HPFPatientWS_PatientService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/medicalRecord")]
        public string McK_EIG_ROI_Client_Web_References_MedicalRecordWS_MedicalRecordService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_MedicalRecordWS_MedicalRecordService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/deficiency")]
        public string McK_EIG_ROI_Client_Web_References_DeficiencyWS_DeficiencyService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_DeficiencyWS_DeficiencyService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/configuration")]
        public string McK_EIG_ROI_Client_Web_References_ConfigurationWS_ConfigurationService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_ConfigurationWS_ConfigurationService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/password")]
        public string McK_EIG_ROI_Client_Web_References_PasswordWS_PasswordService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_PasswordWS_PasswordService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/logout")]
        public string McK_EIG_ROI_Client_Web_References_LogoutWS_LogoutService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_LogoutWS_LogoutService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/document")]
        public string McK_EIG_ROI_Client_Web_References_DocumentWS_DocumentInfoService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_DocumentWS_DocumentInfoService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/authenticationService")]
        public string McK_EIG_ROI_Client_Web_References_AuthenticationWS_AuthenticationService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_AuthenticationWS_AuthenticationService"])));
            }
        }

        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/ROIOutputService")]
        public string McK_EIG_ROI_Client_Web_References_OutputServiceWS_ROIOutputService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_OutputServiceWS_ROIOutputService"])));
            }
        }


        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/ROISupplementalService")]
        public string McK_EIG_ROI_Client_Web_References_ROISupplementalWS_ROISupplementalService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_ROISupplementalWS_ROISupplementalService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/ccdConvert")]
        public string McK_EIG_ROI_Client_Web_References_CcdConversionServiceWS_CcdConversionService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_CcdConversionServiceWS_CcdConversionService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:80/portal/eig/iservices/signin")]
        public string McK_EIG_ROI_Client_Web_References_SigninWS_SigninService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("PORTAL", ((string)(this["McK_EIG_ROI_Client_Web_References_SigninWS_SigninService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/OverdueInvoiceService")]
        public string McK_EIG_ROI_Client_Web_References_OverDueInvoiceWS_OverdueInvoiceService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_OverDueInvoiceWS_OverdueInvoiceService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/ROIAdminService")]
        public string McK_EIG_ROI_Client_Web_References_ROIAdminWS_ROIAdminService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_ROIAdminWS_ROIAdminService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/BillingService")]
        public string McK_EIG_ROI_Client_Web_References_BillingWS_BillingService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_BillingWS_BillingService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/BillingAdminService")]
        public string McK_EIG_ROI_Client_Web_References_BillingAdminWS_BillingAdminService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_BillingAdminWS_BillingAdminService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/RequestService")]
        public string McK_EIG_ROI_Client_Web_References_ROIRequestWS_RequestService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_ROIRequestWS_RequestService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/RequestCoreService")]
        public string McK_EIG_ROI_Client_Web_References_ROIRequestCoreWS_RequestCoreService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_ROIRequestCoreWS_RequestCoreService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/BillingCoreService")]
        public string McK_EIG_ROI_Client_Web_References_BillingCoreWS_BillingCoreService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_BillingCoreWS_BillingCoreService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/SupplementaryService")]
        public string McK_EIG_ROI_Client_Web_References_SupplementaryService_SupplementaryService
        {
            get
            {
                return ((string)(this["McK_EIG_ROI_Client_Web_References_SupplementaryService_SupplementaryService"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/OverdueInvoiceCoreService")]
        public string McK_EIG_ROI_Client_Web_References_OverDueInvoiceCoreWS_OverdueInvoiceCoreService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_OverDueInvoiceCoreWS_OverdueInvoiceCoreService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/SupplementaryService")]
        public string McK_EIG_ROI_Client_Web_References_ROISupplementaryWS_SupplementaryService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_ROISupplementaryWS_SupplementaryService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/RequestorService")]
        public string McK_EIG_ROI_Client_Web_References_ROIRequestorWS_RequestorService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_ROIRequestorWS_RequestorService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/roi/services/ConfigureDaysService")]
        public string McK_EIG_ROI_Client_WebReferences_ConfigureDaysWS_ConfigureDaysService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_WebReferences_ConfigureDaysWS_ConfigureDaysService"])));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8080/alert/services/AlertService")]
        public string McK_EIG_ROI_Client_Web_References_AlertServiceWS_AlertService
        {
            get
            {
                return McK.EIG.ROI.Client.Base.Controller.INIFile.getURLWithINIValues("ROI", ((string)(this["McK_EIG_ROI_Client_Web_References_AlertServiceWS_AlertService"])));
            }
        }
    }
}
