//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace McK.EIG.ROI.Client.Web_References.OverDueInvoiceWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ROIOverDueInvoiceSoapBinding", Namespace="urn:eig.mckesson.com")]
    public partial class OverdueInvoiceServiceWse : McK.EIG.ROI.Client.Base.Controller.CustomWebServicesClientProtocol //Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private @long transactionIdField;
        
        private SecurityHeaderType securityField;
        
        private System.Threading.SendOrPostCallback searchPastDueInvoicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback regenerateInvoiceAndLetterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OverdueInvoiceServiceWse() {
            this.Url = global::McK.EIG.ROI.Client.Properties.Settings.Default.McK_EIG_ROI_Client_Web_References_OverDueInvoiceWS_OverdueInvoiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public @long transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        public SecurityHeaderType Security {
            get {
                return this.securityField;
            }
            set {
                this.securityField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event searchPastDueInvoicesCompletedEventHandler searchPastDueInvoicesCompleted;
        
        /// <remarks/>
        public event regenerateInvoiceAndLetterCompletedEventHandler regenerateInvoiceAndLetterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/searchPastDueInvoices", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("searchPastDueInvoiceResult")]
        public SearchPastDueInvoiceResult searchPastDueInvoices(SearchPastDueInvoiceCriteria PastDueInvoiceCriteria) {
            object[] results = this.Invoke("searchPastDueInvoices", new object[] {
                        PastDueInvoiceCriteria});
            return ((SearchPastDueInvoiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void searchPastDueInvoicesAsync(SearchPastDueInvoiceCriteria PastDueInvoiceCriteria) {
            this.searchPastDueInvoicesAsync(PastDueInvoiceCriteria, null);
        }
        
        /// <remarks/>
        public void searchPastDueInvoicesAsync(SearchPastDueInvoiceCriteria PastDueInvoiceCriteria, object userState) {
            if ((this.searchPastDueInvoicesOperationCompleted == null)) {
                this.searchPastDueInvoicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchPastDueInvoicesOperationCompleted);
            }
            this.InvokeAsync("searchPastDueInvoices", new object[] {
                        PastDueInvoiceCriteria}, this.searchPastDueInvoicesOperationCompleted, userState);
        }
        
        private void OnsearchPastDueInvoicesOperationCompleted(object arg) {
            if ((this.searchPastDueInvoicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchPastDueInvoicesCompleted(this, new searchPastDueInvoicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/regenerateInvoiceAndLetter", RequestElementName="RegenerateInvoiceAndLetter", RequestNamespace="urn:eig.mckesson.com", ResponseElementName="RegenerateInvoiceAndLetterResponse", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("overDueDocInfoList")]
        public OverDueDocInfoList regenerateInvoiceAndLetter(InvoiceAndLetterInfo InvoiceAndLetterInfo, bool forPreview) {
            object[] results = this.Invoke("regenerateInvoiceAndLetter", new object[] {
                        InvoiceAndLetterInfo,
                        forPreview});
            return ((OverDueDocInfoList)(results[0]));
        }
        
        /// <remarks/>
        public void regenerateInvoiceAndLetterAsync(InvoiceAndLetterInfo InvoiceAndLetterInfo, bool forPreview) {
            this.regenerateInvoiceAndLetterAsync(InvoiceAndLetterInfo, forPreview, null);
        }
        
        /// <remarks/>
        public void regenerateInvoiceAndLetterAsync(InvoiceAndLetterInfo InvoiceAndLetterInfo, bool forPreview, object userState) {
            if ((this.regenerateInvoiceAndLetterOperationCompleted == null)) {
                this.regenerateInvoiceAndLetterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregenerateInvoiceAndLetterOperationCompleted);
            }
            this.InvokeAsync("regenerateInvoiceAndLetter", new object[] {
                        InvoiceAndLetterInfo,
                        forPreview}, this.regenerateInvoiceAndLetterOperationCompleted, userState);
        }
        
        private void OnregenerateInvoiceAndLetterOperationCompleted(object arg) {
            if ((this.regenerateInvoiceAndLetterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.regenerateInvoiceAndLetterCompleted(this, new regenerateInvoiceAndLetterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("transactionId", Namespace="urn:eig.mckesson.com", IsNullable=false)]
    public partial class @long : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    [System.Xml.Serialization.XmlRootAttribute("Security", Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "", IsNullable=false)]
    public partial class SecurityHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class OverDueDocInfo {
        
        private long idField;
        
        private string nameField;
        
        private string typeField;
        
        private string requestorGroupingKeyField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string requestorGroupingKey {
            get {
                return this.requestorGroupingKeyField;
            }
            set {
                this.requestorGroupingKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class OverDueDocInfoList {
        
        private OverDueDocInfo[] overDueDocInfosField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("overDueDocInfos")]
        public OverDueDocInfo[] overDueDocInfos {
            get {
                return this.overDueDocInfosField;
            }
            set {
                this.overDueDocInfosField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class propertiesMap {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class attributesMap {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Item {
        
        private string typeField;
        
        private attributesMap[] attributesField;
        
        private Item[] childItemField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes")]
        public attributesMap[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childItem")]
        public Item[] childItem {
            get {
                return this.childItemField;
            }
            set {
                this.childItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class RequestorInvoices {
        
        private long[] invoiceIdsField;
        
        private long requestorIdField;
        
        private string requestorNameField;
        
        private string requestorTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoiceIds")]
        public long[] invoiceIds {
            get {
                return this.invoiceIdsField;
            }
            set {
                this.invoiceIdsField = value;
            }
        }
        
        /// <remarks/>
        public long requestorId {
            get {
                return this.requestorIdField;
            }
            set {
                this.requestorIdField = value;
            }
        }
        
        /// <remarks/>
        public string requestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        public string requestorType {
            get {
                return this.requestorTypeField;
            }
            set {
                this.requestorTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class InvoiceAndLetterInfo {
        
        private RequestorInvoices[] invoicesField;
        
        private long invoiceTemplateIdField;
        
        private long requestorLetterTemplateIdField;
        
        private string[] reqLetterNotesField;
        
        private string[] invoiceNotesField;
        
        private Item letterField;
        
        private Item newInvoiceField;
        
        private long pastInvIdsField;
        
        private bool pastInvIdsFieldSpecified;
        
        private bool isLetterField;
        
        private bool isNewInvoiceField;
        
        private bool isPastInvoiceField;
        
        private propertiesMap[] propertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoices")]
        public RequestorInvoices[] invoices {
            get {
                return this.invoicesField;
            }
            set {
                this.invoicesField = value;
            }
        }
        
        /// <remarks/>
        public long invoiceTemplateId {
            get {
                return this.invoiceTemplateIdField;
            }
            set {
                this.invoiceTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        public long requestorLetterTemplateId {
            get {
                return this.requestorLetterTemplateIdField;
            }
            set {
                this.requestorLetterTemplateIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reqLetterNotes")]
        public string[] reqLetterNotes {
            get {
                return this.reqLetterNotesField;
            }
            set {
                this.reqLetterNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("invoiceNotes")]
        public string[] invoiceNotes {
            get {
                return this.invoiceNotesField;
            }
            set {
                this.invoiceNotesField = value;
            }
        }
        
        /// <remarks/>
        public Item letter {
            get {
                return this.letterField;
            }
            set {
                this.letterField = value;
            }
        }
        
        /// <remarks/>
        public Item newInvoice {
            get {
                return this.newInvoiceField;
            }
            set {
                this.newInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public long pastInvIds {
            get {
                return this.pastInvIdsField;
            }
            set {
                this.pastInvIdsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pastInvIdsSpecified {
            get {
                return this.pastInvIdsFieldSpecified;
            }
            set {
                this.pastInvIdsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isLetter {
            get {
                return this.isLetterField;
            }
            set {
                this.isLetterField = value;
            }
        }
        
        /// <remarks/>
        public bool isNewInvoice {
            get {
                return this.isNewInvoiceField;
            }
            set {
                this.isNewInvoiceField = value;
            }
        }
        
        /// <remarks/>
        public bool isPastInvoice {
            get {
                return this.isPastInvoiceField;
            }
            set {
                this.isPastInvoiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public propertiesMap[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class PastDueInvoice {
        
        private string billingLocationField;
        
        private long invoiceNumberField;
        
        private long requestIdField;
        
        private double overdueAmountField;
        
        private string requestorNameField;
        
        private string phoneNumberField;
        
        private string requestorTypeField;
        
        private long requestorIdField;
        
        private long overDueDaysField;
        
        /// <remarks/>
        public string billingLocation {
            get {
                return this.billingLocationField;
            }
            set {
                this.billingLocationField = value;
            }
        }
        
        /// <remarks/>
        public long invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        public double overdueAmount {
            get {
                return this.overdueAmountField;
            }
            set {
                this.overdueAmountField = value;
            }
        }
        
        /// <remarks/>
        public string requestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        public string phoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string requestorType {
            get {
                return this.requestorTypeField;
            }
            set {
                this.requestorTypeField = value;
            }
        }
        
        /// <remarks/>
        public long requestorId {
            get {
                return this.requestorIdField;
            }
            set {
                this.requestorIdField = value;
            }
        }
        
        /// <remarks/>
        public long overDueDays {
            get {
                return this.overDueDaysField;
            }
            set {
                this.overDueDaysField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class SearchPastDueInvoiceResult {
        
        private bool maxCountExceededField;
        
        private PastDueInvoice[] pastDueInvoiceListField;
        
        /// <remarks/>
        public bool maxCountExceeded {
            get {
                return this.maxCountExceededField;
            }
            set {
                this.maxCountExceededField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PastDueInvoice[] PastDueInvoiceList {
            get {
                return this.pastDueInvoiceListField;
            }
            set {
                this.pastDueInvoiceListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class SearchPastDueInvoiceCriteria {
        
        private string[] billingLocationsField;
        
        private long[] requestorTypesField;
        
        private string requestorNameField;
        
        private long overDueFromField;
        
        private long overDueToField;
        
        private bool overDueToFieldSpecified;
        
        private OverDueRestriction overDueRestrictionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("billingLocations")]
        public string[] billingLocations {
            get {
                return this.billingLocationsField;
            }
            set {
                this.billingLocationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requestorTypes")]
        public long[] requestorTypes {
            get {
                return this.requestorTypesField;
            }
            set {
                this.requestorTypesField = value;
            }
        }
        
        /// <remarks/>
        public string requestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        public long overDueFrom {
            get {
                return this.overDueFromField;
            }
            set {
                this.overDueFromField = value;
            }
        }
        
        /// <remarks/>
        public long overDueTo {
            get {
                return this.overDueToField;
            }
            set {
                this.overDueToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool overDueToSpecified {
            get {
                return this.overDueToFieldSpecified;
            }
            set {
                this.overDueToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public OverDueRestriction overDueRestriction {
            get {
                return this.overDueRestrictionField;
            }
            set {
                this.overDueRestrictionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public enum OverDueRestriction {
        
        /// <remarks/>
        GREATER,
        
        /// <remarks/>
        BETWEEN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void searchPastDueInvoicesCompletedEventHandler(object sender, searchPastDueInvoicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchPastDueInvoicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchPastDueInvoicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchPastDueInvoiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchPastDueInvoiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void regenerateInvoiceAndLetterCompletedEventHandler(object sender, regenerateInvoiceAndLetterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class regenerateInvoiceAndLetterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal regenerateInvoiceAndLetterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OverDueDocInfoList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OverDueDocInfoList)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591