# mpf-roi.properties
# This file contains properties that will not change during customer installs.
jdbc.driver=net.sourceforge.jtds.jdbc.Driver
jdbc.url=jdbc:jtds:sqlserver://MPFDATA/cabinet
db.user=roi
db.password=roipazz

######################Tenant Config Starts################################
#Configuration written here works based on the tenant id 

#mpf.tenant
default.tenant=mpf

# configurations related to mpf-core server
mpf.core.server.hostname=localhost
mpf.core.server.port=18080
mpf.core.server.context=/mpfcore/

######################Tenant Config Ends################################

#configurations related to MPFW server
mpfw.core.server.protocol=http
mpfw.core.server.hostname=localhost
mpfw.core.server.port=18080

##Email appender configuration
email.appender.from.address=roi@mckesson.com
email.appender.to.address=TOADDRESS@mckesson.com
email.appender.SMTPHost=SMTPHOST
email.appender.Subject=EMAIL Alerting Service

# Logging properties
log.dir=D:\\mckesson\\logs\\roi
max.filesize=100MB
max.file.history=9
int.log.level=WARN

# log4j properties

# Root logger option
log4j.rootLogger=WARN, eigLogAppender, eigMetricsAppender, eigConsoleAppender, eigDatabaseAppender

# Categories
# Uncomment to turn on debug logging for EIG code.
log4j.category.com.mckesson.eig=INFO,eigLogAppender
 
# eigLogAppender configuration
log4j.appender.eigLogAppender=org.apache.log4j.RollingFileAppender
log4j.appender.eigLogAppender.File=${log.dir}/mpf.roi.log
log4j.appender.eigLogAppender.Append=true
log4j.appender.eigLogAppender.MaxFileSize=10MB
log4j.appender.eigLogAppender.MaxBackupIndex=10
log4j.appender.eigLogAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.eigLogAppender.layout.ConversionPattern=%d{DATE} | %t | %X{ipaddress} | %X{JOBID}| %X{userid} | %X{transactionid} | %c{1} | %m%n

# eigMetricsAppender configuration
log4j.appender.eigMetricsAppender=org.apache.log4j.RollingFileAppender
log4j.appender.eigMetricsAppender.File=${log.dir}/mpf.roi.metrics.log
log4j.appender.eigMetricsAppender.Append=true
log4j.appender.eigMetricsAppender.MaxFileSize=10MB
log4j.appender.eigMetricsAppender.MaxBackupIndex=10
log4j.appender.eigMetricsAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.eigMetricsAppender.layout.ConversionPattern=%d{DATE} | %t | %X{ipaddress} | %X{JOBID}| %X{userid} | %X{transactionid} | %c{1} | %m%n

# eigConsoleAppender configuration
log4j.appender.eigConsoleAppender=org.apache.log4j.ConsoleAppender
log4j.appender.eigConsoleAppender.Threshold=DEBUG
log4j.appender.eigConsoleAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.eigConsoleAppender.layout.ConversionPattern=%d{DATE} | %t | %X{ipaddress} | %X{JOBID}| %X{userid} | %X{transactionid} | %c{1} | %m%n

# eigDatabaseAppender configuration
log4j.appender.eigDatabaseAppender=org.apache.log4j.jdbc.JDBCAppender
log4j.appender.eigDatabaseAppender.Driver=${jdbc.driver}
log4j.appender.eigDatabaseAppender.URL=${jdbc.url}
log4j.appender.eigDatabaseAppender.User=${db.user}
log4j.appender.eigDatabaseAppender.Password=${db.password}
log4j.appender.eigDatabaseAppender.Threshold=ERROR
log4j.appender.eigDatabaseAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.eigDatabaseAppender.layout.ConversionPattern=INSERT INTO SYSERRORS_GLOBAL(GlobalID,OCCURRED,ERROR_TYPE,ERROR_DESC) VALUES ('%X{GLOBAL_ID}',getDate(),'%p','%m%throwable{short}%n' )
