# Look and Feel config
# possible look and feels
# Windows - com.sun.java.swing.plaf.windows.WindowsLookAndFeel
# Motif - com.sun.java.swing.plaf.motif.MotifLookAndFeel
# Synth - javax.swing.plaf.synth.SynthLookAndFeel

look.and.feel=com.sun.java.swing.plaf.windows.WindowsLookAndFeel

#JBoss Server Config
jboss.home=C:\ROI\Jboss
jboss.server.run.bat.path=\bin\run.conf.bat
jboss.server.server.xml.path=\server\default\deploy\jbossweb.sar\server.xml

#DB Config
db.connection.config.path=\server\default\deploy\ROI-ds.xml
output.db.connection.config.path=\server\default\deploy\eig-db-ds.xml
activeMQ.config.path=\server\default\var\config\broker-config.xml
smb.connection.config.path=\server\default\deploy\portal.war\WEB-INF\classes\config\services\smb.config
hpfw.connection.config.path=\server\default\deploy\portal.war\WEB-INF\classes\config\hibernate\hibernate.properties
hpfw.logging.config.path=\server\default\deploy\portal.war\WEB-INF\classes\config\logging\\log.config

#Client config
click.once.path=\server\default\deploy\ROOT.war\ROIClient\Application Files
client.config.file=\McK.EIG.ROI.Client.App.exe.config
client.config.version=/McK.EIG.ROI.Client.App_16_2_0_64

#If dev.environment is set to true
# 	Client installer config file path will be taken directly from 'client.config.file'
#If dev.environment is set to false
# 	Client installer config file path will be taken relative to 'jboss.home' ('jboss.home' + 'click.once.path' + 'client.config.file')
dev.environment=false

#FaxService config
fax.service.home=C:\ROI\FaxService
fax.service.config.path=\McK.EIG.Common.Output.Fax.exe.config

#OutputService config
output.jboss.home=C:\ROI\output.jboss
output.end.point.type.path=\server\default\var\config\com\mckesson\eig\output\endpoint-types.xml
output.end.point.defs.path=\server\default\var\config\com\mckesson\eig\output\endpoint-defs.xml
output.authuntication.config.path=\server\default\var\config\com\mckesson\eig\output\output-spring-ext.eig.xml
output.spring.config.path=\server\default\var\config\com\mckesson\eig\output\output-spring.xml

roi.authentication.wsdl.url=\server\default\var\config\com\mckesson\eig\roi\spring.xml
inuse.authentication.wsdl.url=\server\default\var\config\com\mckesson\eig\inuse\spring.xml

roi.server.installed=true
roi.client.installer.installed=true
fax.server.installed=true
output.server.installed=true

server.url=127.0.0.1

#Output JBoss Server Config
output.jboss.server.run.bat.path=\bin\run.conf.bat

#Log File path
roi.jndi.name=java:/ROI_DS
output.jndi.name=java:/Eig-Output-DS

roi.log.path=\server\default\var\config\com\mckesson\eig\roi\logging.xml
roi.inuse.log.path=\server\default\var\config\com\mckesson\eig\inuse\logging.xml
#CR - 381,475
#roi.audit.log.path=\server\default\var\config\com\mckesson\eig\audit\logging\audit.logging.xml
roi.alert.log.path=\server\default\var\config\com\mckesson\eig\alert\logging.xml

output.audit.log.path=\server\default\var\config\com\mckesson\eig\audit\logging\audit.logging.xml
output.log.path=\server\default\var\config\com\mckesson\eig\output\output-logging.xml

#mpfw configuration
mpfw.logging.production.path=\server\default\deploy\portal.war\WEB-INF\classes\config\logging\log4j-production.properties
mpfw.logging.staging.path=\server\default\deploy\portal.war\WEB-INF\classes\config\logging\log4j-staging.properties
mpfw.web.xml.path=\server\default\deploy\portal.war\WEB-INF\web.xml
mpfw.encryption.config.path=\server\default\deploy\portal.war\WEB-INF\classes\config\services\encryption.config
mpfw.log.file.location=\server\default\log\MPFWLog\eig.log
mpfw.encryption.class=com.mckesson.eig.common.password.PasswordMD5
output.mpfw.application.name=MPFW_IN_OPSVC
roi.mpfw.application.name=MPFW_IN_ROI
# global name for error logging, argument {0} denotes application name, {1} denotes machine name
logging.global.name.format={0}:{1}
server.login.conf.file=\server\default\conf\login-config.xml
server.eig.outputsettings.file=\server\default\var\config\com\mckesson\eig\output\output-settings.properties
