#region Copyright © 2010 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
/* 
BEGIN-COPYRIGHT-COMMENT Do not remove or modify this line!

* Copyright © 2010 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
* Use of this software and related documentation is governed by a license agreement. 
* This material contains confidential, proprietary and trade secret information of 
* McKesson Information Solutions and is protected under United States
* and international copyright and other intellectual property laws. 
* Use, disclosure, reproduction, modification, distribution, or storage
* in a retrieval system in any form or by any means is prohibited without the 
* prior express written permission of McKesson Information Solutions.

END-COPYRIGHT-COMMENT  Do not remove or modify this line! 
*/
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace McK.EIG.ROI.Client.Web_References.DocumentWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DocumentSoapBinding", Namespace="urn:eig.mckesson.com")]
    public partial class DocumentInfoServiceWse : McK.EIG.ROI.Client.Base.Controller.CustomWebServicesClientProtocol // Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback getImnetsByImnetOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocumentListInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDocumentInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DocumentInfoServiceWse()
        {
            this.Url = global::McK.EIG.ROI.Client.Properties.Settings.Default.McK_EIG_ROI_Client_Web_References_DocumentWS_DocumentInfoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getImnetsByImnetCompletedEventHandler getImnetsByImnetCompleted;
        
        /// <remarks/>
        public event getDocumentListInfoCompletedEventHandler getDocumentListInfoCompleted;
        
        /// <remarks/>
        public event getDocumentInfoCompletedEventHandler getDocumentInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result")]
        public string getImnetsByImnet(string userid, string userpassword, string time, string key, string imnet) {
            object[] results = this.Invoke("getImnetsByImnet", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        imnet});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getImnetsByImnetAsync(string userid, string userpassword, string time, string key, string imnet) {
            this.getImnetsByImnetAsync(userid, userpassword, time, key, imnet, null);
        }
        
        /// <remarks/>
        public void getImnetsByImnetAsync(string userid, string userpassword, string time, string key, string imnet, object userState) {
            if ((this.getImnetsByImnetOperationCompleted == null)) {
                this.getImnetsByImnetOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetImnetsByImnetOperationCompleted);
            }
            this.InvokeAsync("getImnetsByImnet", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        imnet}, this.getImnetsByImnetOperationCompleted, userState);
        }
        
        private void OngetImnetsByImnetOperationCompleted(object arg) {
            if ((this.getImnetsByImnetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getImnetsByImnetCompleted(this, new getImnetsByImnetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("chart")]
        public chartType getDocumentListInfo(string userid, string userpassword, string time, string key, string epn, string gpi, string mrn, string facility, string encounter, System.DateTime fromDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool fromDateSpecified, System.DateTime toDate, [System.Xml.Serialization.XmlIgnoreAttribute()] bool toDateSpecified, string recordview) {
            object[] results = this.Invoke("getDocumentListInfo", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        epn,
                        gpi,
                        mrn,
                        facility,
                        encounter,
                        fromDate,
                        fromDateSpecified,
                        toDate,
                        toDateSpecified,
                        recordview});
            return ((chartType)(results[0]));
        }
        
        /// <remarks/>
        public void getDocumentListInfoAsync(string userid, string userpassword, string time, string key, string epn, string gpi, string mrn, string facility, string encounter, System.DateTime fromDate, bool fromDateSpecified, System.DateTime toDate, bool toDateSpecified, string recordview) {
            this.getDocumentListInfoAsync(userid, userpassword, time, key, epn, gpi, mrn, facility, encounter, fromDate, fromDateSpecified, toDate, toDateSpecified, recordview, null);
        }
        
        /// <remarks/>
        public void getDocumentListInfoAsync(string userid, string userpassword, string time, string key, string epn, string gpi, string mrn, string facility, string encounter, System.DateTime fromDate, bool fromDateSpecified, System.DateTime toDate, bool toDateSpecified, string recordview, object userState) {
            if ((this.getDocumentListInfoOperationCompleted == null)) {
                this.getDocumentListInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocumentListInfoOperationCompleted);
            }
            this.InvokeAsync("getDocumentListInfo", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        epn,
                        gpi,
                        mrn,
                        facility,
                        encounter,
                        fromDate,
                        fromDateSpecified,
                        toDate,
                        toDateSpecified,
                        recordview}, this.getDocumentListInfoOperationCompleted, userState);
        }
        
        private void OngetDocumentListInfoOperationCompleted(object arg) {
            if ((this.getDocumentListInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocumentListInfoCompleted(this, new getDocumentListInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("documentInfoResult")]
        public documentInfoType getDocumentInfo(string userid, string userpassword, string time, string key, string duid) {
            object[] results = this.Invoke("getDocumentInfo", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        duid});
            return ((documentInfoType)(results[0]));
        }
        
        /// <remarks/>
        public void getDocumentInfoAsync(string userid, string userpassword, string time, string key, string duid) {
            this.getDocumentInfoAsync(userid, userpassword, time, key, duid, null);
        }
        
        /// <remarks/>
        public void getDocumentInfoAsync(string userid, string userpassword, string time, string key, string duid, object userState) {
            if ((this.getDocumentInfoOperationCompleted == null)) {
                this.getDocumentInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDocumentInfoOperationCompleted);
            }
            this.InvokeAsync("getDocumentInfo", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        duid}, this.getDocumentInfoOperationCompleted, userState);
        }
        
        private void OngetDocumentInfoOperationCompleted(object arg) {
            if ((this.getDocumentInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDocumentInfoCompleted(this, new getDocumentInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class chartType {
        
        private bool enterprisepatientField;
        
        private facilitypatientsType facilitypatientsField;
        
        /// <remarks/>
        public bool enterprisepatient {
            get {
                return this.enterprisepatientField;
            }
            set {
                this.enterprisepatientField = value;
            }
        }
        
        /// <remarks/>
        public facilitypatientsType facilitypatients {
            get {
                return this.facilitypatientsField;
            }
            set {
                this.facilitypatientsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class facilitypatientsType {
        
        private facilitypatientType facilitypatientField;
        
        /// <remarks/>
        public facilitypatientType facilitypatient {
            get {
                return this.facilitypatientField;
            }
            set {
                this.facilitypatientField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class facilitypatientType {
        
        private string nameField;
        
        private string gpiField;
        
        private string epnField;
        
        private globaldocumentsType globaldocumentsField;
        
        private encountersType encountersField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string gpi {
            get {
                return this.gpiField;
            }
            set {
                this.gpiField = value;
            }
        }
        
        /// <remarks/>
        public string epn {
            get {
                return this.epnField;
            }
            set {
                this.epnField = value;
            }
        }
        
        /// <remarks/>
        public globaldocumentsType globaldocuments {
            get {
                return this.globaldocumentsField;
            }
            set {
                this.globaldocumentsField = value;
            }
        }
        
        /// <remarks/>
        public encountersType encounters {
            get {
                return this.encountersField;
            }
            set {
                this.encountersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class globaldocumentsType {
        
        private globaldocumentType globaldocumentField;
        
        /// <remarks/>
        public globaldocumentType globaldocument {
            get {
                return this.globaldocumentField;
            }
            set {
                this.globaldocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class globaldocumentType {
        
        private documentType documentInfoField;
        
        /// <remarks/>
        public documentType documentInfo {
            get {
                return this.documentInfoField;
            }
            set {
                this.documentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class documentType {
        
        private string duidField;
        
        private string edidField;
        
        private bool globalField;
        
        private string nameField;
        
        private string facilityField;
        
        private string subtitleField;
        
        private System.DateTime datetimeField;
        
        private versionsType versionsField;
        
        /// <remarks/>
        public string duid {
            get {
                return this.duidField;
            }
            set {
                this.duidField = value;
            }
        }
        
        /// <remarks/>
        public string edid {
            get {
                return this.edidField;
            }
            set {
                this.edidField = value;
            }
        }
        
        /// <remarks/>
        public bool global {
            get {
                return this.globalField;
            }
            set {
                this.globalField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        public versionsType versions {
            get {
                return this.versionsField;
            }
            set {
                this.versionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class versionsType {
        
        private versionType versionField;
        
        /// <remarks/>
        public versionType version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class versionType {
        
        private string numberField;
        
        private System.DateTime datetimeField;
        
        private string pagecountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime datetime {
            get {
                return this.datetimeField;
            }
            set {
                this.datetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string pagecount {
            get {
                return this.pagecountField;
            }
            set {
                this.pagecountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class documentInfoType {
        
        private string pageCountField;
        
        private string duidField;
        
        private string facilityField;
        
        private string versionField;
        
        private string nameField;
        
        private string subtitleField;
        
        private System.DateTime dateTimeField;
        
        private string encounterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string pageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
        
        /// <remarks/>
        public string duid {
            get {
                return this.duidField;
            }
            set {
                this.duidField = value;
            }
        }
        
        /// <remarks/>
        public string facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string subtitle {
            get {
                return this.subtitleField;
            }
            set {
                this.subtitleField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        public string encounter {
            get {
                return this.encounterField;
            }
            set {
                this.encounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class documentsType {
        
        private documentType documentInfoField;
        
        /// <remarks/>
        public documentType documentInfo {
            get {
                return this.documentInfoField;
            }
            set {
                this.documentInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class encounterType {
        
        private string facilityField;
        
        private string numberField;
        
        private documentsType documentsField;
        
        /// <remarks/>
        public string facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        public documentsType documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class encountersType {
        
        private encounterType encountersField;
        
        /// <remarks/>
        public encounterType encounters {
            get {
                return this.encountersField;
            }
            set {
                this.encountersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getImnetsByImnetCompletedEventHandler(object sender, getImnetsByImnetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getImnetsByImnetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getImnetsByImnetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getDocumentListInfoCompletedEventHandler(object sender, getDocumentListInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocumentListInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocumentListInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public chartType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((chartType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getDocumentInfoCompletedEventHandler(object sender, getDocumentInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDocumentInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDocumentInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public documentInfoType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((documentInfoType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591