#THIS FILE MAPS THE WEB SERVICE SECURITIES TO ROI SECURITY
#MODIFY THIS FILE ACCORDINGLY WHEN AXIS.WSDD IS MODIFIED
#THE SECURITY CODE IS NOT SUPPOSED TO CHANGE AND SHOULD BE IN SYNC
#WITH THE DATABASE

roi_administration.admin=6101
roi_administration.access=6102
roi_administration.createRequest=6103
roi_administration.modifyRequest=6104
roi_administration.deleteRequest=6105
roi_administration.vip=6106
roi_administration.cancelRequest=6107
roi_administration.pendRequest=6108
roi_administration.denyRequest=6109
roi_administration.adjustCharges=6110
roi_administration.runReport=6111
roi_administration.runReport=6111
ROIPatientService.vip=6106
