package com.mckesson.eig.roi.admin.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory;

import com.mckesson.eig.roi.admin.model.BillingPaymentInfo;
import com.mckesson.eig.roi.admin.model.BillingTemplate;
import com.mckesson.eig.roi.admin.model.BillingTemplatesList;
import com.mckesson.eig.roi.admin.model.BillingTier;
import com.mckesson.eig.roi.admin.model.BillingTiersList;
import com.mckesson.eig.roi.admin.model.FeeType;
import com.mckesson.eig.roi.admin.model.FeeTypesList;
import com.mckesson.eig.roi.admin.model.MediaType;
import com.mckesson.eig.roi.admin.model.MediaTypesList;
import com.mckesson.eig.roi.admin.model.PaymentMethod;
import com.mckesson.eig.roi.admin.model.PaymentMethodList;
import com.mckesson.eig.roi.admin.model.TaxPerFacility;
import com.mckesson.eig.roi.admin.model.TaxPerFacilityList;

/**
 * This class was generated by Apache CXF 3.0.2 2021-09-22T20:04:40.066+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:eig.mckesson.com", name = "BillingAdminService")
/*@XmlSeeAlso({
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class,
        org.w3._2000._09.xmldsig_.ObjectFactory.class,
        org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class,
        ObjectFactory.class})*/
public interface BillingAdminService {

    @WebMethod(action = "urn:eig.mckesson.com/createTaxPerFacility")
    @RequestWrapper(localName = "createTaxPerFacility", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.CreateTaxPerFacility")
    @ResponseWrapper(localName = "createTaxPerFacilityResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.CreateTaxPerFacilityResponse")
    @WebResult(name = "TaxPerFacility", targetNamespace = "urn:eig.mckesson.com")
    public long createTaxPerFacility(
            @WebParam(name = "TaxPerFacility", targetNamespace = "urn:eig.mckesson.com") TaxPerFacility taxPerFacility);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveMediaType")
    @RequestWrapper(localName = "retrieveMediaType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveMediaType")
    @ResponseWrapper(localName = "retrieveMediaTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveMediaTypeResponse")
    @WebResult(name = "mediaTypeDetails", targetNamespace = "urn:eig.mckesson.com")
    public MediaType retrieveMediaType(
            @WebParam(name = "mediaTypeId", targetNamespace = "urn:eig.mckesson.com") long mediaTypeId);

    @WebMethod(action = "urn:eig.mckesson.com/deletePaymentMethod")
    @RequestWrapper(localName = "deletePaymentMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.DeletePaymentMethod")
    @ResponseWrapper(localName = "deletePaymentMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.DeletePaymentMethodResponse")
    public void deletePaymentMethod(
            @WebParam(name = "paymentMethodId", targetNamespace = "urn:eig.mckesson.com") long paymentMethodId);

    @WebMethod(action = "urn:eig.mckesson.com/createBillingTemplate")
    @RequestWrapper(localName = "createBillingTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.CreateBillingTemplate")
    @ResponseWrapper(localName = "createBillingTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.CreateBillingTemplateResponse")
    @WebResult(name = "billingTemplateId", targetNamespace = "urn:eig.mckesson.com")
    public long createBillingTemplate(
            @WebParam(name = "billingTemplate", targetNamespace = "urn:eig.mckesson.com") BillingTemplate billingTemplate);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllPaymentMethods")
    @RequestWrapper(localName = "retrieveAllPaymentMethods", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllPaymentMethods")
    @ResponseWrapper(localName = "retrieveAllPaymentMethodsResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllPaymentMethodsResponse")
    @WebResult(name = "paymentMethods", targetNamespace = "urn:eig.mckesson.com")
    public PaymentMethodList retrieveAllPaymentMethods(
            @WebParam(name = "detailedFetch", targetNamespace = "urn:eig.mckesson.com") boolean detailedFetch);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveBillingTemplate")
    @RequestWrapper(localName = "retrieveBillingTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveBillingTemplate")
    @ResponseWrapper(localName = "retrieveBillingTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveBillingTemplateResponse")
    @WebResult(name = "billingTemplate", targetNamespace = "urn:eig.mckesson.com")
    public BillingTemplate retrieveBillingTemplate(
            @WebParam(name = "billingTemplateId", targetNamespace = "urn:eig.mckesson.com") long billingTemplateId);

    @WebMethod(action = "urn:eig.mckesson.com/updateBillingTemplate")
    @RequestWrapper(localName = "updateBillingTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.UpdateBillingTemplate")
    @ResponseWrapper(localName = "updateBillingTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.UpdateBillingTemplateResponse")
    @WebResult(name = "billingTemplate", targetNamespace = "urn:eig.mckesson.com")
    public BillingTemplate updateBillingTemplate(
            @WebParam(name = "billingTemplate", targetNamespace = "urn:eig.mckesson.com") BillingTemplate billingTemplate);

    @WebMethod(action = "urn:eig.mckesson.com/updateTaxPerFacility")
    @RequestWrapper(localName = "updateTaxPerFacility", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.UpdateTaxPerFacility")
    @ResponseWrapper(localName = "updateTaxPerFacilityResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.UpdateTaxPerFacilityResponse")
    @WebResult(name = "TaxPerFacility", targetNamespace = "urn:eig.mckesson.com")
    public TaxPerFacility updateTaxPerFacility(
            @WebParam(name = "TaxPerFacility", targetNamespace = "urn:eig.mckesson.com") TaxPerFacility taxPerFacility);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveTaxPerFacility")
    @RequestWrapper(localName = "retrieveTaxPerFacility", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveTaxPerFacility")
    @ResponseWrapper(localName = "retrieveTaxPerFacilityResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveTaxPerFacilityResponse")
    @WebResult(name = "TaxPerFacility", targetNamespace = "urn:eig.mckesson.com")
    public TaxPerFacility retrieveTaxPerFacility(
            @WebParam(name = "TaxPerFacilityId", targetNamespace = "urn:eig.mckesson.com") long taxPerFacilityId);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllTaxPerFacilities")
    @RequestWrapper(localName = "retrieveAllTaxPerFacilities", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllTaxPerFacilities")
    @ResponseWrapper(localName = "retrieveAllTaxPerFacilitiesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllTaxPerFacilitiesResponse")
    @WebResult(name = "TaxPerFacilityList", targetNamespace = "urn:eig.mckesson.com")
    public TaxPerFacilityList retrieveAllTaxPerFacilities();

    @WebMethod(action = "urn:eig.mckesson.com/createPaymentMethod")
    @RequestWrapper(localName = "createPaymentMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.CreatePaymentMethod")
    @ResponseWrapper(localName = "createPaymentMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.CreatePaymentMethodResponse")
    @WebResult(name = "paymentMethodId", targetNamespace = "urn:eig.mckesson.com")
    public long createPaymentMethod(
            @WebParam(name = "paymentMethodDetails", targetNamespace = "urn:eig.mckesson.com") PaymentMethod paymentMethodDetails);

    @WebMethod(action = "urn:eig.mckesson.com/deleteBillingTier")
    @RequestWrapper(localName = "deleteBillingTier", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.DeleteBillingTier")
    @ResponseWrapper(localName = "deleteBillingTierResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.DeleteBillingTierResponse")
    public void deleteBillingTier(
            @WebParam(name = "billingTierId", targetNamespace = "urn:eig.mckesson.com") long billingTierId);

    @WebMethod(action = "urn:eig.mckesson.com/updateMediaType")
    @RequestWrapper(localName = "updateMediaType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.UpdateMediaType")
    @ResponseWrapper(localName = "updateMediaTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.UpdateMediaTypeResponse")
    @WebResult(name = "mediaTypeDetails", targetNamespace = "urn:eig.mckesson.com")
    public MediaType updateMediaType(
            @WebParam(name = "mediaTypeDetails", targetNamespace = "urn:eig.mckesson.com") MediaType mediaTypeDetails);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveFeeType")
    @RequestWrapper(localName = "retrieveFeeType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveFeeType")
    @ResponseWrapper(localName = "retrieveFeeTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveFeeTypeResponse")
    @WebResult(name = "feeTypeDetails", targetNamespace = "urn:eig.mckesson.com")
    public FeeType retrieveFeeType(
            @WebParam(name = "feeTypeId", targetNamespace = "urn:eig.mckesson.com") long feeTypeId);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllBillingTiers")
    @RequestWrapper(localName = "retrieveAllBillingTiers", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllBillingTiers")
    @ResponseWrapper(localName = "retrieveAllBillingTiersResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllBillingTiersResponse")
    @WebResult(name = "billingTiers", targetNamespace = "urn:eig.mckesson.com")
    public BillingTiersList retrieveAllBillingTiers(
            @WebParam(name = "loadAssociation", targetNamespace = "urn:eig.mckesson.com") boolean loadAssociation);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveBillingTier")
    @RequestWrapper(localName = "retrieveBillingTier", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveBillingTier")
    @ResponseWrapper(localName = "retrieveBillingTierResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveBillingTierResponse")
    @WebResult(name = "bt", targetNamespace = "urn:eig.mckesson.com")
    public BillingTier retrieveBillingTier(
            @WebParam(name = "billingTierId", targetNamespace = "urn:eig.mckesson.com") long billingTierId);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllMediaTypes")
    @RequestWrapper(localName = "retrieveAllMediaTypes", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllMediaTypes")
    @ResponseWrapper(localName = "retrieveAllMediaTypesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllMediaTypesResponse")
    @WebResult(name = "mediaTypes", targetNamespace = "urn:eig.mckesson.com")
    public MediaTypesList retrieveAllMediaTypes(
            @WebParam(name = "detailedFetch", targetNamespace = "urn:eig.mckesson.com") boolean detailedFetch);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllBillingTemplates")
    @RequestWrapper(localName = "retrieveAllBillingTemplates", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllBillingTemplates")
    @ResponseWrapper(localName = "retrieveAllBillingTemplatesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllBillingTemplatesResponse")
    @WebResult(name = "billingTemplates", targetNamespace = "urn:eig.mckesson.com")
    public BillingTemplatesList retrieveAllBillingTemplates(
            @WebParam(name = "getAssociation", targetNamespace = "urn:eig.mckesson.com") boolean getAssociation);

    @WebMethod(action = "urn:eig.mckesson.com/deleteBillingTemplate")
    @RequestWrapper(localName = "deleteBillingTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.DeleteBillingTemplate")
    @ResponseWrapper(localName = "deleteBillingTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.DeleteBillingTemplateResponse")
    public void deleteBillingTemplate(
            @WebParam(name = "billingTemplateId", targetNamespace = "urn:eig.mckesson.com") long billingTemplateId);

    @WebMethod(action = "urn:eig.mckesson.com/createMediaType")
    @RequestWrapper(localName = "createMediaType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.CreateMediaType")
    @ResponseWrapper(localName = "createMediaTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.CreateMediaTypeResponse")
    @WebResult(name = "mediaTypeId", targetNamespace = "urn:eig.mckesson.com")
    public long createMediaType(
            @WebParam(name = "mediaTypeDetails", targetNamespace = "urn:eig.mckesson.com") MediaType mediaTypeDetails);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllFeeTypes")
    @RequestWrapper(localName = "retrieveAllFeeTypes", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllFeeTypes")
    @ResponseWrapper(localName = "retrieveAllFeeTypesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllFeeTypesResponse")
    @WebResult(name = "feeTypes", targetNamespace = "urn:eig.mckesson.com")
    public FeeTypesList retrieveAllFeeTypes(
            @WebParam(name = "detailedFetch", targetNamespace = "urn:eig.mckesson.com") boolean detailedFetch);

    @WebMethod(action = "urn:eig.mckesson.com/deleteFeeType")
    @RequestWrapper(localName = "deleteFeeType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.DeleteFeeType")
    @ResponseWrapper(localName = "deleteFeeTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.DeleteFeeTypeResponse")
    public void deleteFeeType(
            @WebParam(name = "feeTypeId", targetNamespace = "urn:eig.mckesson.com") long feeTypeId);

    @WebMethod(action = "urn:eig.mckesson.com/updatePaymentMethod")
    @RequestWrapper(localName = "updatePaymentMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.UpdatePaymentMethod")
    @ResponseWrapper(localName = "updatePaymentMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.UpdatePaymentMethodResponse")
    @WebResult(name = "paymentMethodDetails", targetNamespace = "urn:eig.mckesson.com")
    public PaymentMethod updatePaymentMethod(
            @WebParam(name = "paymentMethodDetails", targetNamespace = "urn:eig.mckesson.com") PaymentMethod paymentMethodDetails);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveBillingTiersByMediaTypeName")
    @RequestWrapper(localName = "retrieveBillingTiersByMediaTypeName", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveBillingTiersByMediaTypeName")
    @ResponseWrapper(localName = "retrieveBillingTiersByMediaTypeNameResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveBillingTiersByMediaTypeNameResponse")
    @WebResult(name = "billingTiers", targetNamespace = "urn:eig.mckesson.com")
    public BillingTiersList retrieveBillingTiersByMediaTypeName(
            @WebParam(name = "mediaTypeName", targetNamespace = "urn:eig.mckesson.com") String mediaTypeName);

    @WebMethod(action = "urn:eig.mckesson.com/deleteMediaType")
    @RequestWrapper(localName = "deleteMediaType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.DeleteMediaType")
    @ResponseWrapper(localName = "deleteMediaTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.DeleteMediaTypeResponse")
    public void deleteMediaType(
            @WebParam(name = "mediaTypeId", targetNamespace = "urn:eig.mckesson.com") long mediaTypeId);

    @WebMethod(action = "urn:eig.mckesson.com/updateBillingTier")
    @RequestWrapper(localName = "updateBillingTier", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.UpdateBillingTier")
    @ResponseWrapper(localName = "updateBillingTierResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.UpdateBillingTierResponse")
    @WebResult(name = "bt", targetNamespace = "urn:eig.mckesson.com")
    public BillingTier updateBillingTier(
            @WebParam(name = "bt", targetNamespace = "urn:eig.mckesson.com") BillingTier bt);

    @WebMethod(action = "urn:eig.mckesson.com/createBillingTier")
    @RequestWrapper(localName = "createBillingTier", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.CreateBillingTier")
    @ResponseWrapper(localName = "createBillingTierResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.CreateBillingTierResponse")
    @WebResult(name = "bt", targetNamespace = "urn:eig.mckesson.com")
    public BillingTier createBillingTier(
            @WebParam(name = "bt", targetNamespace = "urn:eig.mckesson.com") BillingTier bt);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllTaxPerFacilitiesByUser")
    @RequestWrapper(localName = "retrieveAllTaxPerFacilitiesByUser", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveAllTaxPerFacilitiesByUser")
    @ResponseWrapper(localName = "retrieveAllTaxPerFacilitiesByUserResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveAllTaxPerFacilitiesByUserResponse")
    @WebResult(name = "TaxPerFacilityList", targetNamespace = "urn:eig.mckesson.com")
    public TaxPerFacilityList retrieveAllTaxPerFacilitiesByUser(
            @WebParam(name = "UserId") String userId);

    @WebMethod(action = "urn:eig.mckesson.com/deleteTaxPerFacility")
    @RequestWrapper(localName = "deleteTaxPerFacility", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.DeleteTaxPerFacility")
    @ResponseWrapper(localName = "deleteTaxPerFacilityResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.DeleteTaxPerFacilityResponse")
    public void deleteTaxPerFacility(
            @WebParam(name = "TaxPerFacilityId", targetNamespace = "urn:eig.mckesson.com") long taxPerFacilityId);

    @WebMethod(action = "urn:eig.mckesson.com/retrieveBillingAndPaymentInfo")
    @RequestWrapper(localName = "retrieveBillingAndPaymentInfo", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrieveBillingAndPaymentInfo")
    @ResponseWrapper(localName = "retrieveBillingAndPaymentInfoResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrieveBillingAndPaymentInfoResponse")
    @WebResult(name = "billingPaymentInfo", targetNamespace = "urn:eig.mckesson.com")
    public BillingPaymentInfo retrieveBillingAndPaymentInfo(
            @WebParam(name = "requestorTypeId", targetNamespace = "urn:eig.mckesson.com") long requestorTypeId);

    @WebMethod(action = "urn:eig.mckesson.com/createFeeType")
    @RequestWrapper(localName = "createFeeType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.CreateFeeType")
    @ResponseWrapper(localName = "createFeeTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.CreateFeeTypeResponse")
    @WebResult(name = "feeTypeId", targetNamespace = "urn:eig.mckesson.com")
    public long createFeeType(
            @WebParam(name = "feeTypeDetails", targetNamespace = "urn:eig.mckesson.com") FeeType feeTypeDetails);

    @WebMethod(action = "urn:eig.mckesson.com/retrievePaymentMethod")
    @RequestWrapper(localName = "retrievePaymentMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.RetrievePaymentMethod")
    @ResponseWrapper(localName = "retrievePaymentMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.RetrievePaymentMethodResponse")
    @WebResult(name = "paymentMethodDetails", targetNamespace = "urn:eig.mckesson.com")
    public PaymentMethod retrievePaymentMethod(
            @WebParam(name = "paymentMethodId", targetNamespace = "urn:eig.mckesson.com") long paymentMethodId);

    @WebMethod(action = "urn:eig.mckesson.com/updateFeeType")
    @RequestWrapper(localName = "updateFeeType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsRequestWrapper.UpdateFeeType")
    @ResponseWrapper(localName = "updateFeeTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingAdminService.wsResponseWrapper.UpdateFeeTypeResponse")
    @WebResult(name = "feeTypeDetails", targetNamespace = "urn:eig.mckesson.com")
    public FeeType updateFeeType(
            @WebParam(name = "feeTypeDetails", targetNamespace = "urn:eig.mckesson.com") FeeType feeTypeDetails);

}
