package com.mckesson.eig.roi.admin.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.mckesson.eig.roi.supplementary.model.AttachmentDeleteStatusList;
import com.mckesson.eig.roi.supplementary.model.AttachmentInfoList;
import com.mckesson.eig.roi.supplementary.model.AttachmentSequenceList;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2021-09-21T19:55:25.213+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:eig.mckesson.com", name = "ROIAttachmentService")
//@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, ObjectFactory.class})
public interface ROIAttachmentService {
    
    /** 
     * This FailedReasonCode is defined in class ImageFile of RecordsManagement
     * Code base make sure both are same.
     * 
     */
    public enum FailedReasonCode {

        FILE_MISSING("FILE_MISSING"),
        FILE_DELETE_ACCESS_DENIED("FILE_DELETE_ACCESS_DENIED"),
        DELETION_UNSUCCESSFUL("DELETION_UNSUCCESSFUL"),
        DELETION_SUCCESSFUL("DELETION_SUCCESSFUL"),
        FILE_EXISTS_AFTER_DELETION("FILE_EXISTS_AFTER_DELETION");
        
        String _deleteLog;
        FailedReasonCode(String log) {
            _deleteLog = log;
        }
        
        @Override
        public String toString() {
            return _deleteLog;
        }
    }
    
    
    
    
    @WebMethod(action = "urn:eig.mckesson.com/getAllAttachments")
    @RequestWrapper(localName = "getAllAttachments", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAttachmentService.wsRequestWrapper.GetAllAttachments")
    @ResponseWrapper(localName = "getAllAttachmentsResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAttachmentService.wsResponseWrapper.GetAllAttachmentsResponse")
    @WebResult(name = "AttachmentInfoList", targetNamespace = "urn:eig.mckesson.com")
    public AttachmentInfoList getAllAttachments(
        @WebParam(name = "mrn", targetNamespace = "urn:eig.mckesson.com")
        String mrn,
        @WebParam(name = "facility", targetNamespace = "urn:eig.mckesson.com")
        String facility
    );

    @WebMethod(action = "urn:eig.mckesson.com/deleteROIAttachments")
    @RequestWrapper(localName = "deleteROIAttachments", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAttachmentService.wsRequestWrapper.DeleteROIAttachments")
    @ResponseWrapper(localName = "deleteROIAttachmentsResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAttachmentService.wsResponseWrapper.DeleteROIAttachmentsResponse")
    @WebResult(name = "AttachmentDeleteStatusList", targetNamespace = "urn:eig.mckesson.com")
    public AttachmentDeleteStatusList deleteROIAttachments(
        @WebParam(name = "AttachmentSequenceList", targetNamespace = "urn:eig.mckesson.com")
        AttachmentSequenceList attachmentSequenceList
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAttachmentsInfo")
    @RequestWrapper(localName = "retrieveAttachmentsInfo", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAttachmentService.wsRequestWrapper.RetrieveAttachmentsInfo")
    @ResponseWrapper(localName = "retrieveAttachmentsInfoResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAttachmentService.wsResponseWrapper.RetrieveAttachmentsInfoResponse")
    @WebResult(name = "AttachmentInfoList", targetNamespace = "urn:eig.mckesson.com")
    public AttachmentInfoList retrieveAttachmentsInfo(
        @WebParam(name = "mrn", targetNamespace = "urn:eig.mckesson.com")
        String mrn,
        @WebParam(name = "facility", targetNamespace = "urn:eig.mckesson.com")
        String facility,
        @WebParam(name = "encounter", targetNamespace = "urn:eig.mckesson.com")
        String encounter
    );
}
