package com.mckesson.eig.roi.admin.service;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.mckesson.eig.roi.admin.model.AttachmentLocation;
import com.mckesson.eig.roi.admin.model.Country;
import com.mckesson.eig.roi.admin.model.DeliveryMethod;
import com.mckesson.eig.roi.admin.model.DeliveryMethodList;
import com.mckesson.eig.roi.admin.model.Designation;
import com.mckesson.eig.roi.admin.model.DocTypeAuditList;
import com.mckesson.eig.roi.admin.model.DocTypeDesignations;
import com.mckesson.eig.roi.admin.model.GenderList;
import com.mckesson.eig.roi.admin.model.InvoiceDueDays;
import com.mckesson.eig.roi.admin.model.LetterTemplate;
import com.mckesson.eig.roi.admin.model.LetterTemplateList;
import com.mckesson.eig.roi.admin.model.Note;
import com.mckesson.eig.roi.admin.model.NotesList;
import com.mckesson.eig.roi.admin.model.OutputServerProperties;
import com.mckesson.eig.roi.admin.model.ROIAppData;
import com.mckesson.eig.roi.admin.model.Reason;
import com.mckesson.eig.roi.admin.model.Reasons;
import com.mckesson.eig.roi.admin.model.ReasonsList;
import com.mckesson.eig.roi.admin.model.RequestStatusMap;
import com.mckesson.eig.roi.admin.model.RequestorType;
import com.mckesson.eig.roi.admin.model.RequestorTypesList;
import com.mckesson.eig.roi.admin.model.SSNMask;
import com.mckesson.eig.roi.admin.model.User;
import com.mckesson.eig.roi.admin.model.Weight;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2021-09-21T19:52:49.455+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:eig.mckesson.com", name = "ROIAdminService")
//@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, ObjectFactory.class})
public interface ROIAdminService {

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllGenders")
    @RequestWrapper(localName = "retrieveAllGenders", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllGenders")
    @ResponseWrapper(localName = "retrieveAllGendersResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllGendersResponse")
    @WebResult(name = "genderList", targetNamespace = "urn:eig.mckesson.com")
    public GenderList retrieveAllGenders();

    @WebMethod(action = "urn:eig.mckesson.com/retrieveDesignations")
    @RequestWrapper(localName = "retrieveDesignations", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveDesignations")
    @ResponseWrapper(localName = "retrieveDesignationsResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveDesignationsResponse")
    @WebResult(name = "docTypeDesignation", targetNamespace = "urn:eig.mckesson.com")
    public DocTypeDesignations retrieveDesignations(
        @WebParam(name = "codeSetId", targetNamespace = "urn:eig.mckesson.com")
        long codeSetId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllLetterTemplates")
    @RequestWrapper(localName = "retrieveAllLetterTemplates", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllLetterTemplates")
    @ResponseWrapper(localName = "retrieveAllLetterTemplatesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllLetterTemplatesResponse")
    @WebResult(name = "letterTemplates", targetNamespace = "urn:eig.mckesson.com")
    public LetterTemplateList retrieveAllLetterTemplates();

    @WebMethod(action = "urn:eig.mckesson.com/updateInvoiceDueDays")
    @RequestWrapper(localName = "updateInvoiceDue", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateInvoiceDue")
    @ResponseWrapper(localName = "updateInvoiceDueResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateInvoiceDueResponse")
    @WebResult(name = "InvoiceDue", targetNamespace = "urn:eig.mckesson.com")
    public InvoiceDueDays updateInvoiceDueDays(
        @WebParam(name = "InvoiceDue", targetNamespace = "urn:eig.mckesson.com")
        InvoiceDueDays invoiceDue
    );

    @WebMethod(action = "urn:eig.mckesson.com/getUser")
    @RequestWrapper(localName = "getUser", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.GetUserResponse")
    @WebResult(name = "user", targetNamespace = "urn:eig.mckesson.com")
    public User getUser(
        @WebParam(name = "userId", targetNamespace = "urn:eig.mckesson.com")
        String userId
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateUnbillableRequestFlag")
    @RequestWrapper(localName = "updateUnbillableRequestFlag", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateUnbillableRequestFlag")
    @ResponseWrapper(localName = "updateUnbillableRequestFlagResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateUnbillableRequestFlagResponse")
    public void updateUnbillableRequestFlag(
        @WebParam(name = "checked", targetNamespace = "urn:eig.mckesson.com")
        boolean checked
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateSSNMask")
    @RequestWrapper(localName = "updateSSNMask", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateSSNMask")
    @ResponseWrapper(localName = "updateSSNMaskResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateSSNMaskResponse")
    @WebResult(name = "maskDetails", targetNamespace = "urn:eig.mckesson.com")
    public SSNMask updateSSNMask(
        @WebParam(name = "maskDetails", targetNamespace = "urn:eig.mckesson.com")
        SSNMask maskDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveReasonsByStatus")
    @RequestWrapper(localName = "retrieveReasonsByStatus", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveReasonsByStatus")
    @ResponseWrapper(localName = "retrieveReasonsByStatusResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponsetWrapper.RetrieveReasonsByStatusResponse")
    @WebResult(name = "statusReason", targetNamespace = "urn:eig.mckesson.com")
    public Reasons retrieveReasonsByStatus(
        @WebParam(name = "statusId", targetNamespace = "urn:eig.mckesson.com")
        int statusId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllDeliveryMethods")
    @RequestWrapper(localName = "retrieveAllDeliveryMethods", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllDeliveryMethods")
    @ResponseWrapper(localName = "retrieveAllDeliveryMethodsResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllDeliveryMethodsResponse")
    @WebResult(name = "deliveryMethods", targetNamespace = "urn:eig.mckesson.com")
    public DeliveryMethodList retrieveAllDeliveryMethods(
        @WebParam(name = "detailedFetch", targetNamespace = "urn:eig.mckesson.com")
        boolean detailedFetch
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateLetterTemplate")
    @RequestWrapper(localName = "updateLetterTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateLetterTemplate")
    @ResponseWrapper(localName = "updateLetterTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateLetterTemplateResponse")
    @WebResult(name = "letterTemplateDetails", targetNamespace = "urn:eig.mckesson.com")
    public LetterTemplate updateLetterTemplate(
        @WebParam(name = "letterTemplateDetails", targetNamespace = "urn:eig.mckesson.com")
        LetterTemplate letterTemplateDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveRequestorType")
    @RequestWrapper(localName = "retrieveRequestorType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveRequestorType")
    @ResponseWrapper(localName = "retrieveRequestorTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveRequestorTypeResponse")
    @WebResult(name = "requestorType", targetNamespace = "urn:eig.mckesson.com")
    public RequestorType retrieveRequestorType(
        @WebParam(name = "requestorTypeId", targetNamespace = "urn:eig.mckesson.com")
        long requestorTypeId
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateWeight")
    @RequestWrapper(localName = "updateWeight", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateWeight")
    @ResponseWrapper(localName = "updateWeightResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateWeightResponse")
    @WebResult(name = "weightDetails", targetNamespace = "urn:eig.mckesson.com")
    public Weight updateWeight(
        @WebParam(name = "weightDetails", targetNamespace = "urn:eig.mckesson.com")
        Weight weightDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/enableOutputService")
    @RequestWrapper(localName = "enableOutputService", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.EnableOutputService")
    @ResponseWrapper(localName = "enableOutputServiceResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.EnableOutputServiceResponse")
    public void enableOutputService(
        @WebParam(name = "enabled", targetNamespace = "urn:eig.mckesson.com")
        boolean enabled
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveDeliveryMethod")
    @RequestWrapper(localName = "retrieveDeliveryMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveDeliveryMethod")
    @ResponseWrapper(localName = "retrieveDeliveryMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveDeliveryMethodResponse")
    @WebResult(name = "deliveryMethodDetails", targetNamespace = "urn:eig.mckesson.com")
    public DeliveryMethod retrieveDeliveryMethod(
        @WebParam(name = "deliveryMethodId", targetNamespace = "urn:eig.mckesson.com")
        long deliveryMethodId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveLetterTemplate")
    @RequestWrapper(localName = "retrieveLetterTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveLetterTemplate")
    @ResponseWrapper(localName = "retrieveLetterTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveLetterTemplateResponse")
    @WebResult(name = "letterTemplateDetails", targetNamespace = "urn:eig.mckesson.com")
    public LetterTemplate retrieveLetterTemplate(
        @WebParam(name = "letterTemplateId", targetNamespace = "urn:eig.mckesson.com")
        long letterTemplateId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveMUDocTypes")
    @RequestWrapper(localName = "retrieveMUDocTypes", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveMUDocTypes")
    @ResponseWrapper(localName = "retrieveMUDocTypesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveMUDocTypesResponse")
    @WebResult(name = "mudoclist", targetNamespace = "urn:eig.mckesson.com")
    public List<String> retrieveMUDocTypes();

    @WebMethod(action = "urn:eig.mckesson.com/deleteReason")
    @RequestWrapper(localName = "deleteReason", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.DeleteReason")
    @ResponseWrapper(localName = "deleteReasonResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.DeleteReasonResponse")
    public void deleteReason(
        @WebParam(name = "reasonId", targetNamespace = "urn:eig.mckesson.com")
        long reasonId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveUnbillableRequestFlag")
    @RequestWrapper(localName = "retrieveUnbillableRequestFlag", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveUnbillableRequestFlag")
    @ResponseWrapper(localName = "retrieveUnbillableRequestFlagResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveUnbillableRequestFlagResponse")
    @WebResult(name = "checked", targetNamespace = "urn:eig.mckesson.com")
    public boolean retrieveUnbillableRequestFlag();

    @WebMethod(action = "urn:eig.mckesson.com/updateRequestorType")
    @RequestWrapper(localName = "updateRequestorType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateRequestorType")
    @ResponseWrapper(localName = "updateRequestorTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateRequestorTypeResponse")
    @WebResult(name = "requestorType", targetNamespace = "urn:eig.mckesson.com")
    public RequestorType updateRequestorType(
        @WebParam(name = "requestorType", targetNamespace = "urn:eig.mckesson.com")
        RequestorType requestorType
    );

    @WebMethod(action = "urn:eig.mckesson.com/createLetterTemplate")
    @RequestWrapper(localName = "createLetterTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.CreateLetterTemplate")
    @ResponseWrapper(localName = "createLetterTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.CreateLetterTemplateResponse")
    @WebResult(name = "letterTemplateId", targetNamespace = "urn:eig.mckesson.com")
    public long createLetterTemplate(
        @WebParam(name = "letterTemplateDetails", targetNamespace = "urn:eig.mckesson.com")
        LetterTemplate letterTemplateDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateDeliveryMethod")
    @RequestWrapper(localName = "updateDeliveryMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateDeliveryMethod")
    @ResponseWrapper(localName = "updateDeliveryMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateDeliveryMethodResponse")
    @WebResult(name = "deliveryMethodDetails", targetNamespace = "urn:eig.mckesson.com")
    public DeliveryMethod updateDeliveryMethod(
        @WebParam(name = "deliveryMethodDetails", targetNamespace = "urn:eig.mckesson.com")
        DeliveryMethod deliveryMethodDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/designateDocumentTypes")
    @RequestWrapper(localName = "designateDocumentTypes", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.DesignateDocumentTypes")
    @ResponseWrapper(localName = "designateDocumentTypesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.DesignateDocumentTypesResponse")
    public void designateDocumentTypes(
        @WebParam(name = "codeSetId", targetNamespace = "urn:eig.mckesson.com")
        long codeSetId,
        @WebParam(name = "docTypeDesignation", targetNamespace = "urn:eig.mckesson.com")
        DocTypeDesignations docTypeDesignation,
        @WebParam(name = "docTypeAuditList", targetNamespace = "urn:eig.mckesson.com")
        DocTypeAuditList docTypeAuditList
    );

    @WebMethod(action = "urn:eig.mckesson.com/hasLetterTemplate")
    @RequestWrapper(localName = "hasLetterTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.HasLetterTemplate")
    @ResponseWrapper(localName = "hasLetterTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.HasLetterTemplateResponse")
    @WebResult(name = "hasLetterTemplate", targetNamespace = "urn:eig.mckesson.com")
    public boolean hasLetterTemplate(
        @WebParam(name = "letterType", targetNamespace = "urn:eig.mckesson.com")
        String letterType
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateReason")
    @RequestWrapper(localName = "updateReason", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateReason")
    @ResponseWrapper(localName = "updateReasonResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateReasonResponse")
    @WebResult(name = "reason", targetNamespace = "urn:eig.mckesson.com")
    public Reason updateReason(
        @WebParam(name = "reason", targetNamespace = "urn:eig.mckesson.com")
        Reason reason
    );

    @WebMethod(action = "urn:eig.mckesson.com/deleteRequestorType")
    @RequestWrapper(localName = "deleteRequestorType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.DeleteRequestorType")
    @ResponseWrapper(localName = "deleteRequestorTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.DeleteRequestorTypeResponse")
    public void deleteRequestorType(
        @WebParam(name = "requestorTypeId", targetNamespace = "urn:eig.mckesson.com")
        long requestorTypeId
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateNote")
    @RequestWrapper(localName = "updateNote", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateNote")
    @ResponseWrapper(localName = "updateNoteResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateNoteResponse")
    @WebResult(name = "noteDetails", targetNamespace = "urn:eig.mckesson.com")
    public Note updateNote(
        @WebParam(name = "noteDetails", targetNamespace = "urn:eig.mckesson.com")
        Note noteDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveDocTypeIdsByDesignation")
    @RequestWrapper(localName = "retrieveDocTypeIdsByDesignation", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveDocTypeIdsByDesignation")
    @ResponseWrapper(localName = "retrieveDocTypeIdsByDesignationResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveDocTypeIdsByDesignationResponse")
    @WebResult(name = "designation", targetNamespace = "urn:eig.mckesson.com")
    public Designation retrieveDocTypeIdsByDesignation(
        @WebParam(name = "type", targetNamespace = "urn:eig.mckesson.com")
        String type
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllReasonsByType")
    @RequestWrapper(localName = "retrieveAllReasonsByType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllReasonsByType")
    @ResponseWrapper(localName = "retrieveAllReasonsByTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllReasonsByTypeResponse")
    @WebResult(name = "reasons", targetNamespace = "urn:eig.mckesson.com")
    public ReasonsList retrieveAllReasonsByType(
        @WebParam(name = "type", targetNamespace = "urn:eig.mckesson.com")
        String type
    );

    @WebMethod(action = "urn:eig.mckesson.com/createRequestorType")
    @RequestWrapper(localName = "createRequestorType", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.CreateRequestorType")
    @ResponseWrapper(localName = "createRequestorTypeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.CreateRequestorTypeResponse")
    @WebResult(name = "requestorType", targetNamespace = "urn:eig.mckesson.com")
    public RequestorType createRequestorType(
        @WebParam(name = "requestorType", targetNamespace = "urn:eig.mckesson.com")
        RequestorType requestorType
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllNotes")
    @RequestWrapper(localName = "retrieveAllNotes", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllNotes")
    @ResponseWrapper(localName = "retrieveAllNotesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllNotesResponse")
    @WebResult(name = "notes", targetNamespace = "urn:eig.mckesson.com")
    public NotesList retrieveAllNotes();

    @WebMethod(action = "urn:eig.mckesson.com/createReason")
    @RequestWrapper(localName = "createReason", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.CreateReason")
    @ResponseWrapper(localName = "createReasonResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.CreateReasonResponse")
    @WebResult(name = "reasonId", targetNamespace = "urn:eig.mckesson.com")
    public long createReason(
        @WebParam(name = "reason", targetNamespace = "urn:eig.mckesson.com")
        Reason reason
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveNote")
    @RequestWrapper(localName = "retrieveNote", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveNote")
    @ResponseWrapper(localName = "retrieveNoteResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveNoteResponse")
    @WebResult(name = "noteDetails", targetNamespace = "urn:eig.mckesson.com")
    public Note retrieveNote(
        @WebParam(name = "noteId", targetNamespace = "urn:eig.mckesson.com")
        long noteId
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateCountryCode")
    @RequestWrapper(localName = "updateCountryCode", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateCountryCode")
    @ResponseWrapper(localName = "updateCountryCodeResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateCountryCodeResponse")
    public void updateCountryCode(
        @WebParam(name = "country", targetNamespace = "urn:eig.mckesson.com")
        Country country
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveROIAppData")
    @RequestWrapper(localName = "retrieveROIAppData", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveROIAppData")
    @ResponseWrapper(localName = "retrieveROIAppDataResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveROIAppDataResponse")
    @WebResult(name = "roiAppData", targetNamespace = "urn:eig.mckesson.com")
    public ROIAppData retrieveROIAppData();

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllCountries")
    @RequestWrapper(localName = "retrieveAllCountries", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllCountries")
    @ResponseWrapper(localName = "retrieveAllCountriesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllCountriesResponse")
    @WebResult(name = "country", targetNamespace = "urn:eig.mckesson.com")
    public List<Country> retrieveAllCountries();

    @WebMethod(action = "urn:eig.mckesson.com/createDeliveryMethod")
    @RequestWrapper(localName = "createDeliveryMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.CreateDeliveryMethod")
    @ResponseWrapper(localName = "createDeliveryMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.CreateDeliveryMethodResponse")
    @WebResult(name = "deliveryMethodId", targetNamespace = "urn:eig.mckesson.com")
    public long createDeliveryMethod(
        @WebParam(name = "deliveryMethodDetails", targetNamespace = "urn:eig.mckesson.com")
        DeliveryMethod deliveryMethodDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/deleteLetterTemplate")
    @RequestWrapper(localName = "deleteLetterTemplate", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.DeleteLetterTemplate")
    @ResponseWrapper(localName = "deleteLetterTemplateResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.DeleteLetterTemplateResponse")
    public void deleteLetterTemplate(
        @WebParam(name = "letterTemplateId", targetNamespace = "urn:eig.mckesson.com")
        long letterTemplateId
    );

    @WebMethod(action = "urn:eig.mckesson.com/createNote")
    @RequestWrapper(localName = "createNote", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.CreateNote")
    @ResponseWrapper(localName = "createNoteResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.CreateNoteResponse")
    @WebResult(name = "noteId", targetNamespace = "urn:eig.mckesson.com")
    public long createNote(
        @WebParam(name = "noteDetails", targetNamespace = "urn:eig.mckesson.com")
        Note noteDetails
    );

    @WebMethod(action = "urn:eig.mckesson.com/deleteNote")
    @RequestWrapper(localName = "deleteNote", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.DeleteNote")
    @ResponseWrapper(localName = "deleteNoteResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.DeleteNoteResponse")
    public void deleteNote(
        @WebParam(name = "noteId", targetNamespace = "urn:eig.mckesson.com")
        long noteId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveWeight")
    @RequestWrapper(localName = "retrieveWeight", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveWeight")
    @ResponseWrapper(localName = "retrieveWeightResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveWeightResponse")
    @WebResult(name = "weightDetails", targetNamespace = "urn:eig.mckesson.com")
    public Weight retrieveWeight();

    @WebMethod(action = "urn:eig.mckesson.com/retrieveReason")
    @RequestWrapper(localName = "retrieveReason", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveReason")
    @ResponseWrapper(localName = "retrieveReasonResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveReasonResponse")
    @WebResult(name = "reason", targetNamespace = "urn:eig.mckesson.com")
    public Reason retrieveReason(
        @WebParam(name = "reasonId", targetNamespace = "urn:eig.mckesson.com")
        long reasonId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveOutputServerProperties")
    @RequestWrapper(localName = "retrieveOutputServerProperties", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveOutputServerProperties")
    @ResponseWrapper(localName = "retrieveOutputServerPropertiesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveOutputServerPropertiesResponse")
    @WebResult(name = "outputServerProperties", targetNamespace = "urn:eig.mckesson.com")
    public OutputServerProperties retrieveOutputServerProperties();

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAttachmentLocation")
    @RequestWrapper(localName = "retrieveAttachmentLocation", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAttachmentLocation")
    @ResponseWrapper(localName = "retrieveAttachmentLocationResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAttachmentLocationResponse")
    @WebResult(name = "attachmentLocation", targetNamespace = "urn:eig.mckesson.com")
    public AttachmentLocation retrieveAttachmentLocation();

    @WebMethod(action = "urn:eig.mckesson.com/retrieveSSNMask")
    @RequestWrapper(localName = "retrieveSSNMask", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveSSNMask")
    @ResponseWrapper(localName = "retrieveSSNMaskResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveSSNMaskResponse")
    @WebResult(name = "maskDetails", targetNamespace = "urn:eig.mckesson.com")
    public SSNMask retrieveSSNMask();

    @WebMethod(action = "urn:eig.mckesson.com/saveOutputServerProperties")
    @RequestWrapper(localName = "saveOutputServerProperties", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.SaveOutputServerProperties")
    @ResponseWrapper(localName = "saveOutputServerPropertiesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.SaveOutputServerPropertiesResponse")
    public void saveOutputServerProperties(
        @WebParam(name = "outputServerProperties", targetNamespace = "urn:eig.mckesson.com")
        OutputServerProperties outputServerProperties
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllRequestorTypes")
    @RequestWrapper(localName = "retrieveAllRequestorTypes", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllRequestorTypes")
    @ResponseWrapper(localName = "retrieveAllRequestorTypesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllRequestorTypesResponse")
    @WebResult(name = "requestorTypes", targetNamespace = "urn:eig.mckesson.com")
    public RequestorTypesList retrieveAllRequestorTypes(
        @WebParam(name = "loadAssociations", targetNamespace = "urn:eig.mckesson.com")
        boolean loadAssociations
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveAllRequestStatus")
    @RequestWrapper(localName = "retrieveAllRequestStatus", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveAllRequestStatus")
    @ResponseWrapper(localName = "retrieveAllRequestStatusResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveAllRequestStatusResponse")
    @WebResult(name = "requestStatusMap", targetNamespace = "urn:eig.mckesson.com")
    public RequestStatusMap retrieveAllRequestStatus();

    @WebMethod(action = "urn:eig.mckesson.com/updateAttachmentLocation")
    @RequestWrapper(localName = "updateAttachmentLocation", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.UpdateAttachmentLocation")
    @ResponseWrapper(localName = "updateAttachmentLocationResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.UpdateAttachmentLocationResponse")
    public void updateAttachmentLocation(
        @WebParam(name = "attachmentLocation", targetNamespace = "urn:eig.mckesson.com")
        AttachmentLocation attachmentLocation
    );

    @WebMethod(action = "urn:eig.mckesson.com/deleteDeliveryMethod")
    @RequestWrapper(localName = "deleteDeliveryMethod", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.DeleteDeliveryMethod")
    @ResponseWrapper(localName = "deleteDeliveryMethodResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.DeleteDeliveryMethodResponse")
    public void deleteDeliveryMethod(
        @WebParam(name = "deliveryMethodId", targetNamespace = "urn:eig.mckesson.com")
        long deliveryMethodId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveInvoiceDueDays")
    @RequestWrapper(localName = "retrieveInvoiceDue", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsRequestWrapper.RetrieveInvoiceDue")
    @ResponseWrapper(localName = "retrieveInvoiceDueResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.roiAdminService.wsResponseWrapper.RetrieveInvoiceDueResponse")
    @WebResult(name = "InvoiceDue", targetNamespace = "urn:eig.mckesson.com")
    public InvoiceDueDays retrieveInvoiceDueDays();
}
