; Section ROI Server
[ROI]
protocol = http
ip = emivalid2130
port = 18080
WINDSS_DATABASE=MPFDATA
WINDSS_USER=epr
WINDSS_PSWD=7EA98F6460434AB6

; Section PORTAL Server
[PORTAL]
protocol = http
ip = emivalid2130
port = 18080

