#region Copyright © 2010 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
/* 
BEGIN-COPYRIGHT-COMMENT Do not remove or modify this line!

* Copyright © 2010 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
* Use of this software and related documentation is governed by a license agreement. 
* This material contains confidential, proprietary and trade secret information of 
* McKesson Information Solutions and is protected under United States
* and international copyright and other intellectual property laws. 
* Use, disclosure, reproduction, modification, distribution, or storage
* in a retrieval system in any form or by any means is prohibited without the 
* prior express written permission of McKesson Information Solutions.

END-COPYRIGHT-COMMENT  Do not remove or modify this line! 
*/
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace McK.EIG.ROI.Client.Web_References.DeficiencyWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DeficiencySoapBinding", Namespace="urn:eig.mckesson.com")]
    public partial class DeficiencyServiceWse : McK.EIG.ROI.Client.Base.Controller.CustomWebServicesClientProtocol //Microsoft.Web.Services3.WebServicesClientProtocol 
    {
        
        private System.Threading.SendOrPostCallback getDeficiencyCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getDeficienciesByEncounterOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DeficiencyServiceWse()
        {
            this.Url = global::McK.EIG.ROI.Client.Properties.Settings.Default.McK_EIG_ROI_Client_Web_References_DeficiencyWS_DeficiencyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getDeficiencyCountCompletedEventHandler getDeficiencyCountCompleted;
        
        /// <remarks/>
        public event getDeficienciesByEncounterCompletedEventHandler getDeficienciesByEncounterCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("deficiencies")]
        public deficienciesType getDeficiencyCount(string userid, string userpassword, string time, string key) {
            object[] results = this.Invoke("getDeficiencyCount", new object[] {
                        userid,
                        userpassword,
                        time,
                        key});
            return ((deficienciesType)(results[0]));
        }
        
        /// <remarks/>
        public void getDeficiencyCountAsync(string userid, string userpassword, string time, string key) {
            this.getDeficiencyCountAsync(userid, userpassword, time, key, null);
        }
        
        /// <remarks/>
        public void getDeficiencyCountAsync(string userid, string userpassword, string time, string key, object userState) {
            if ((this.getDeficiencyCountOperationCompleted == null)) {
                this.getDeficiencyCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDeficiencyCountOperationCompleted);
            }
            this.InvokeAsync("getDeficiencyCount", new object[] {
                        userid,
                        userpassword,
                        time,
                        key}, this.getDeficiencyCountOperationCompleted, userState);
        }
        
        private void OngetDeficiencyCountOperationCompleted(object arg) {
            if ((this.getDeficiencyCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDeficiencyCountCompleted(this, new getDeficiencyCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("encounter")]
        public encounter getDeficienciesByEncounter(string userid, string userpassword, string time, string key, string encounter, string facility) {
            object[] results = this.Invoke("getDeficienciesByEncounter", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        encounter,
                        facility});
            return ((encounter)(results[0]));
        }
        
        /// <remarks/>
        public void getDeficienciesByEncounterAsync(string userid, string userpassword, string time, string key, string encounter, string facility) {
            this.getDeficienciesByEncounterAsync(userid, userpassword, time, key, encounter, facility, null);
        }
        
        /// <remarks/>
        public void getDeficienciesByEncounterAsync(string userid, string userpassword, string time, string key, string encounter, string facility, object userState) {
            if ((this.getDeficienciesByEncounterOperationCompleted == null)) {
                this.getDeficienciesByEncounterOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetDeficienciesByEncounterOperationCompleted);
            }
            this.InvokeAsync("getDeficienciesByEncounter", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        encounter,
                        facility}, this.getDeficienciesByEncounterOperationCompleted, userState);
        }
        
        private void OngetDeficienciesByEncounterOperationCompleted(object arg) {
            if ((this.getDeficienciesByEncounterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getDeficienciesByEncounterCompleted(this, new getDeficienciesByEncounterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class deficienciesType {
        
        private personalWorklistsType[] personalField;
        
        private groupWorklistsType[] groupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("personal")]
        public personalWorklistsType[] personal {
            get {
                return this.personalField;
            }
            set {
                this.personalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("group")]
        public groupWorklistsType[] group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class personalWorklistsType {
        
        private string useridField;
        
        private countType[] worklistsField;
        
        private countType[] statusesField;
        
        /// <remarks/>
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("worklist", IsNullable=false)]
        public countType[] worklists {
            get {
                return this.worklistsField;
            }
            set {
                this.worklistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("status", IsNullable=false)]
        public countType[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class countType {
        
        private string nameField;
        
        private string countField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class deficiency {
        
        private string physicianField;
        
        private string typeField;
        
        private string documentField;
        
        private string reasonField;
        
        private string statusField;
        
        private string lockedByField;
        
        /// <remarks/>
        public string physician {
            get {
                return this.physicianField;
            }
            set {
                this.physicianField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public string reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string lockedBy {
            get {
                return this.lockedByField;
            }
            set {
                this.lockedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class encounter {
        
        private string encounterNumberField;
        
        private string facilityCodeField;
        
        private deficiency[] deficiencyListField;
        
        /// <remarks/>
        public string encounterNumber {
            get {
                return this.encounterNumberField;
            }
            set {
                this.encounterNumberField = value;
            }
        }
        
        /// <remarks/>
        public string facilityCode {
            get {
                return this.facilityCodeField;
            }
            set {
                this.facilityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public deficiency[] deficiencyList {
            get {
                return this.deficiencyListField;
            }
            set {
                this.deficiencyListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class groupWorklistsType {
        
        private string nameField;
        
        private countType[] worklistsField;
        
        private countType[] statusesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("worklist", IsNullable=false)]
        public countType[] worklists {
            get {
                return this.worklistsField;
            }
            set {
                this.worklistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("status", IsNullable=false)]
        public countType[] statuses {
            get {
                return this.statusesField;
            }
            set {
                this.statusesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getDeficiencyCountCompletedEventHandler(object sender, getDeficiencyCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDeficiencyCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDeficiencyCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public deficienciesType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((deficienciesType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getDeficienciesByEncounterCompletedEventHandler(object sender, getDeficienciesByEncounterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getDeficienciesByEncounterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getDeficienciesByEncounterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public encounter Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((encounter)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591