#region Copyright © 2010 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
/* 
BEGIN-COPYRIGHT-COMMENT Do not remove or modify this line!

* Copyright © 2010 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
* Use of this software and related documentation is governed by a license agreement. 
* This material contains confidential, proprietary and trade secret information of 
* McKesson Information Solutions and is protected under United States
* and international copyright and other intellectual property laws. 
* Use, disclosure, reproduction, modification, distribution, or storage
* in a retrieval system in any form or by any means is prohibited without the 
* prior express written permission of McKesson Information Solutions.

END-COPYRIGHT-COMMENT  Do not remove or modify this line! 
*/
#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace McK.EIG.ROI.Client.Web_References.HPFPatientWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PatientSoapBinding", Namespace="urn:eig.mckesson.com")]
    public partial class PatientServiceWse : McK.EIG.ROI.Client.Base.Controller.CustomWebServicesClientProtocol //Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private System.Threading.SendOrPostCallback searchPatientsOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchPatientsByExactMatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPatientDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PatientServiceWse()
        {
            this.Url = global::McK.EIG.ROI.Client.Properties.Settings.Default.McK_EIG_ROI_Client_Web_References_HPFPatientWS_PatientService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event searchPatientsCompletedEventHandler searchPatientsCompleted;
        
        /// <remarks/>
        public event searchPatientsByExactMatchCompletedEventHandler searchPatientsByExactMatchCompleted;
        
        /// <remarks/>
        public event getPatientDetailCompletedEventHandler getPatientDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("patientList")]
        public patientList searchPatients(string userid, string userpassword, string time, string key, string lastname, string firstname, string dob, string dateFormat, string ssn, string epn, string mrn, string facility, string encounter) {
            object[] results = this.Invoke("searchPatients", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        lastname,
                        firstname,
                        dob,
                        dateFormat,
                        ssn,
                        epn,
                        mrn,
                        facility,
                        encounter});
            return ((patientList)(results[0]));
        }
        
        /// <remarks/>
        public void searchPatientsAsync(string userid, string userpassword, string time, string key, string lastname, string firstname, string dob, string dateFormat, string ssn, string epn, string mrn, string facility, string encounter) {
            this.searchPatientsAsync(userid, userpassword, time, key, lastname, firstname, dob, dateFormat, ssn, epn, mrn, facility, encounter, null);
        }
        
        /// <remarks/>
        public void searchPatientsAsync(string userid, string userpassword, string time, string key, string lastname, string firstname, string dob, string dateFormat, string ssn, string epn, string mrn, string facility, string encounter, object userState) {
            if ((this.searchPatientsOperationCompleted == null)) {
                this.searchPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchPatientsOperationCompleted);
            }
            this.InvokeAsync("searchPatients", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        lastname,
                        firstname,
                        dob,
                        dateFormat,
                        ssn,
                        epn,
                        mrn,
                        facility,
                        encounter}, this.searchPatientsOperationCompleted, userState);
        }
        
        private void OnsearchPatientsOperationCompleted(object arg) {
            if ((this.searchPatientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchPatientsCompleted(this, new searchPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("facilityPatients")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public facilityPatient[] searchPatientsByExactMatch(string userid, string userpassword, string time, string key, string fullname, string dob, string ssn, string epn, string mrn, string facility, string dateFormat) {
            object[] results = this.Invoke("searchPatientsByExactMatch", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        fullname,
                        dob,
                        ssn,
                        epn,
                        mrn,
                        facility,
                        dateFormat});
            return ((facilityPatient[])(results[0]));
        }
        
        /// <remarks/>
        public void searchPatientsByExactMatchAsync(string userid, string userpassword, string time, string key, string fullname, string dob, string ssn, string epn, string mrn, string facility, string dateFormat) {
            this.searchPatientsByExactMatchAsync(userid, userpassword, time, key, fullname, dob, ssn, epn, mrn, facility, dateFormat, null);
        }
        
        /// <remarks/>
        public void searchPatientsByExactMatchAsync(string userid, string userpassword, string time, string key, string fullname, string dob, string ssn, string epn, string mrn, string facility, string dateFormat, object userState) {
            if ((this.searchPatientsByExactMatchOperationCompleted == null)) {
                this.searchPatientsByExactMatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchPatientsByExactMatchOperationCompleted);
            }
            this.InvokeAsync("searchPatientsByExactMatch", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        fullname,
                        dob,
                        ssn,
                        epn,
                        mrn,
                        facility,
                        dateFormat}, this.searchPatientsByExactMatchOperationCompleted, userState);
        }
        
        private void OnsearchPatientsByExactMatchOperationCompleted(object arg) {
            if ((this.searchPatientsByExactMatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchPatientsByExactMatchCompleted(this, new searchPatientsByExactMatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("facilityPatientDetail")]
        public facilityPatientDetail getPatientDetail(string userid, string userpassword, string time, string key, string mrn, string facility, string dateFormat) {
            object[] results = this.Invoke("getPatientDetail", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        mrn,
                        facility,
                        dateFormat});
            return ((facilityPatientDetail)(results[0]));
        }
        
        /// <remarks/>
        public void getPatientDetailAsync(string userid, string userpassword, string time, string key, string mrn, string facility, string dateFormat) {
            this.getPatientDetailAsync(userid, userpassword, time, key, mrn, facility, dateFormat, null);
        }
        
        /// <remarks/>
        public void getPatientDetailAsync(string userid, string userpassword, string time, string key, string mrn, string facility, string dateFormat, object userState) {
            if ((this.getPatientDetailOperationCompleted == null)) {
                this.getPatientDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPatientDetailOperationCompleted);
            }
            this.InvokeAsync("getPatientDetail", new object[] {
                        userid,
                        userpassword,
                        time,
                        key,
                        mrn,
                        facility,
                        dateFormat}, this.getPatientDetailOperationCompleted, userState);
        }
        
        private void OngetPatientDetailOperationCompleted(object arg) {
            if ((this.getPatientDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPatientDetailCompleted(this, new getPatientDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class patientList {
        
        private facilityPatient[] facilityPatientsField;
        
        private enterprisePatient[] enterprisePatientsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public facilityPatient[] facilityPatients {
            get {
                return this.facilityPatientsField;
            }
            set {
                this.facilityPatientsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public enterprisePatient[] enterprisePatients {
            get {
                return this.enterprisePatientsField;
            }
            set {
                this.enterprisePatientsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(facilityPatientDetail))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class facilityPatient {
        
        private string mrnField;
        
        private string facilityField;
        
        private string epnField;
        
        private string fullNameField;
        
        private string dobField;
        
        private string ssnField;
        
        private string genderField;
        
        private bool patientLockedField;
        
        private bool encounterLockedField;
        
        private bool vipField;
        
        /// <remarks/>
        public string mrn {
            get {
                return this.mrnField;
            }
            set {
                this.mrnField = value;
            }
        }
        
        /// <remarks/>
        public string facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        public string epn {
            get {
                return this.epnField;
            }
            set {
                this.epnField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string dob {
            get {
                return this.dobField;
            }
            set {
                this.dobField = value;
            }
        }
        
        /// <remarks/>
        public string ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        public string gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public bool patientLocked {
            get {
                return this.patientLockedField;
            }
            set {
                this.patientLockedField = value;
            }
        }
        
        /// <remarks/>
        public bool encounterLocked {
            get {
                return this.encounterLockedField;
            }
            set {
                this.encounterLockedField = value;
            }
        }
        
        /// <remarks/>
        public bool vip {
            get {
                return this.vipField;
            }
            set {
                this.vipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class enterprisePatient {
        
        private facilityPatient[] facilityPatientsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public facilityPatient[] facilityPatients {
            get {
                return this.facilityPatientsField;
            }
            set {
                this.facilityPatientsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class facilityPatientDetail : facilityPatient {
        
        private string address1Field;
        
        private string address2Field;
        
        private string address3Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        private string homephoneField;
        
        private string workphoneField;
        
        /// <remarks/>
        public string address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
            }
        }
        
        /// <remarks/>
        public string address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
            }
        }
        
        /// <remarks/>
        public string address3 {
            get {
                return this.address3Field;
            }
            set {
                this.address3Field = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string homephone {
            get {
                return this.homephoneField;
            }
            set {
                this.homephoneField = value;
            }
        }
        
        /// <remarks/>
        public string workphone {
            get {
                return this.workphoneField;
            }
            set {
                this.workphoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void searchPatientsCompletedEventHandler(object sender, searchPatientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public patientList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((patientList)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void searchPatientsByExactMatchCompletedEventHandler(object sender, searchPatientsByExactMatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchPatientsByExactMatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchPatientsByExactMatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public facilityPatient[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((facilityPatient[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getPatientDetailCompletedEventHandler(object sender, getPatientDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPatientDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPatientDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public facilityPatientDetail Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((facilityPatientDetail)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591