var xmlglossaryData = "";
xmlglossaryData += '<?xml version=\"1.0\" encoding=\"utf-8\"?>';
xmlglossaryData += '<html xmlns:MadCap=\"http://www.madcapsoftware.com/Schemas/MadCap.xsd\" MadCap:tocPath=\"\" MadCap:InPreviewMode=\"false\" MadCap:PreloadImages=\"false\" MadCap:RuntimeFileType=\"Glossary\" MadCap:TargetType=\"WebHelp\" lang=\"en-us\" xml:lang=\"en-us\" MadCap:PathToHelpSystem=\"\" MadCap:HelpSystemFileName=\"help.xml\">';
xmlglossaryData += '    <!-- saved from url=(0016)http://localhost -->';
xmlglossaryData += '    <head>';
xmlglossaryData += '        <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />';
xmlglossaryData += '        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />';
xmlglossaryData += '        <link href=\"SkinSupport/Slideshow.css\" rel=\"stylesheet\" type=\"text/css\" MadCap:generated=\"True\" />';
xmlglossaryData += '        <link href=\"SkinSupport/MadCap.css\" rel=\"stylesheet\" type=\"text/css\" MadCap:generated=\"True\" />';
xmlglossaryData += '        <title>Glossary</title>';
xmlglossaryData += '        <link href=\"resources/stylesheets/mck_styles.css\" rel=\"stylesheet\" type=\"text/css\" />';
xmlglossaryData += '        <script src=\"SkinSupport/jquery.min.js\" type=\"text/javascript\">';
xmlglossaryData += '        </script>';
xmlglossaryData += '        <script src=\"SkinSupport/MadCapAll.js\" type=\"text/javascript\">';
xmlglossaryData += '        </script>';
xmlglossaryData += '        <script src=\"SkinSupport/MadCapTopicAll.js\" type=\"text/javascript\">';
xmlglossaryData += '        </script>';
xmlglossaryData += '    </head>';
xmlglossaryData += '    <body style=\"background-color: #fafafa;\">';
xmlglossaryData += '        <div id=\"GlossaryBody\">';
xmlglossaryData += '            <div class=\"GlossaryPageEntry\">';
xmlglossaryData += '                <div class=\"GlossaryPageTerm\">';
xmlglossaryData += '                    <a href=\"javascript:void(0);\" class=\"GlossaryPageTerm\" id=\"MCDropDownHotSpot_949078852_0\" onclick=\"FMCDropDown( this ); FMCScrollToVisible( window, this.parentNode.parentNode ); return false;\">My Term</a>';
xmlglossaryData += '                    <a name=\"949078852_anchor1\">';
xmlglossaryData += '                    </a>';
xmlglossaryData += '                </div>';
xmlglossaryData += '                <div class=\"GlossaryPageDefinition\" id=\"MCDropDownBody_949078852_0\" style=\"display: none;\">My definition</div>';
xmlglossaryData += '            </div>';
xmlglossaryData += '        </div>';
xmlglossaryData += '        <p>&#160;</p>';
xmlglossaryData += '        <script type=\"text/javascript\" src=\"SkinSupport/MadCapBodyEnd.js\">';
xmlglossaryData += '        </script>';
xmlglossaryData += '    </body>';
xmlglossaryData += '</html>';
CMCXmlParser._FilePathToXmlStringMap.Add('glossary', xmlglossaryData);
