log4j.appender.preConversionAppender=org.apache.log4j.RollingFileAppender
log4j.appender.preConversionAppender.File=preConversion.log
log4j.appender.preConversionAppender.layout=org.apache.log4j.PatternLayout
log4j.appender.preConversionAppender.layout.ConversionPattern=%d [%t] %-5p %c{1}.%M - %m%n
log4j.appender.preConversionAppender.MaxFileSize=50MB
log4j.appender.preConversionAppender.MaxBackupIndex=20
log4j.appender.preConversionAppender.append=true

log4j.appender.billing=org.apache.log4j.RollingFileAppender
log4j.appender.billing.File=billingLocation.log
log4j.appender.billing.Append=true
log4j.appender.billing.MaxFileSize=20MB
log4j.appender.billing.MaxBackupIndex=10
log4j.appender.billing.layout=org.apache.log4j.PatternLayout
log4j.appender.billing.layout.ConversionPattern=%m%n

log4j.rootLogger=DEBUG, preConversionAppender
log4j.logger.org.hibernate=OFF
log4j.logger.com.jolbox.bonecp=OFF
log4j.logger.com.mckesson.eig.roi.conversion.billinglocation=INFO, billing