name= conversion
# Log files location
property.filepath=preConversion.log
property.filename =${filepath}
property.filename1 =billingLocation.log
appender.file.type = RollingFile
appender.file.name = preConversionAppender
appender.file.fileName = ${filename}
appender.file.filePattern = ${filepath}/app_%d{yyyyMMdd}.log.gz
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d [%t] %-5p %c{1}.%M - %m%n
appender.file.policies.type = Policies
appender.file.policies.time.type = TimeBasedTriggeringPolicy
appender.file.policies.time.interval = 1
appender.file.policies.time.modulate = true
appender.file.policies.size.type = SizeBasedTriggeringPolicy
appender.file.policies.size.size=50MB
appender.rolling1.type = RollingFile
appender.rolling1.name = billing
appender.rolling1.fileName = ${filename1}
appender.rolling1.filePattern = ${filename1}/app_%d{yyyyMMdd}.log.gz
appender.rolling1.layout.type = PatternLayout
appender.rolling1.layout.pattern =  %d [%t] %-5p %c{1}.%M - %m%n
appender.rolling1.policies.type = Policies
appender.rolling1.policies.time.type = TimeBasedTriggeringPolicy
appender.rolling1.policies.time.interval = 1
appender.rolling1.policies.time.modulate = true
appender.rolling1.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling1.policies.size.size=50MB
rootLogger.level = debug
rootLogger.appenderRef.rolling.ref = preConversionAppender
logger.appender.name = billingLocation
logger.appender.level = info
logger.appender.appenderRef.sss.ref = billing
logger.hibernate.name=org.hibernate
logger.hibernate.level=OFF
logger.bonecp.name =com.jolbox.bonecp.provider.BoneCPConnectionProvider
logger.bonecp.level = OFF