#THIS FILE MAPS THE CONTAINS THE MAXIMUM SIZE OF THE TEXT FILEDS
#TO BE USED IN VALIDATION AND AUDDIT CONSTANTS

audit.action.code=I
audit.facility.code=E_P_R_S
description.length.max=256

#LetterTemplate
letter.template.document.upload.path=C:\StarTeamWorkingFolders\eig\roi\src\server\res
letter.template.document.download.path=C:\StarTeamWorkingFolders\eig\roi\src\server\res
letter.template.document.type=.rtf

#nonHpfPatient
patient_audit_action_code = 2
vip.security.id = 6106
patient.search.max.count = 500

#requestor
requestor.search.max.count = 500
requestor.dob.added.hours = 2

#request
request.status.authreceived = Auth Received
request.status.logged = Logged
request.status.completed = Completed
request.status.denied = Denied
request.status.canceled = Canceled
requeset.status.peneded = Pended
request.status.prebilled = Pre-billed

request.status.authreceived.id = 1
request.status.logged.id = 2
request.status.completed.id = 3
request.status.denied.id = 4
request.status.canceled.id = 5
request.status.pended.id = 6
request.status.prebilled.id = 7

request.audit.action.code.view = 8
request.audit.action.code.create = 1
request.audit.action.code.update = 2
request.audit.action.code.delete = 3


#ssnmask
ssn.mask.seq = -1

#request lov org id
org.id = 1

#Reports
reports.audit.action.code=9

#logon
logon.mask.by=*
open.office.port=8100
open.office.home=C:\3rdparty\open.office
pdf.encryption.password=roi

#tat
report.sname = CCD_pat_info
report.cpi.seq = 3rd Party EHR
report.pat.seq = HPF

#plugin db connection
#plugin.min.db.connection=1
#plugin.max.db.connection=1

#overdue invoices
invoice.due.date.format=MM/dd/yyyy
invoice.due.date.time.format=MM/dd/yyyy hh:mm:ss a
invoice.locale.language=en
invoice.locale.region=US

#database bacth exxecution of sql 
database.sql.batch.size=100