[Bootstrap]
buildid=320m18(Build:9502)
ProductBuildid=9502
ProductCode={5A13987D-55F4-4271-A40E-76AC9B1B38FD}
UpgradeCode={7C35B9AB-2CE3-4C18-BE7C-5B97EA089EB3}
ALLUSERS=1
BASISINSTALLLOCATION=D:\tools\Open Office 3.2\OpenOffice.org 3\Basis\
FINDPRODUCT=Software\OpenOffice.org\OpenOffice.org\3.2\{5A13987D-55F4-4271-A40E-76AC9B1B38FD}
INSTALLLOCATION=D:\tools\Open Office 3.2\
OFFICEINSTALLLOCATION=D:\tools\Open Office 3.2\OpenOffice.org 3\
UREINSTALLLOCATION=D:\tools\Open Office 3.2\OpenOffice.org 3\URE\
