package com.mckesson.eig.roi.billing.service;

import java.util.Date;
import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.mckesson.eig.roi.billing.model.ChargeHistoryList;
import com.mckesson.eig.roi.billing.model.DocInfo;
import com.mckesson.eig.roi.billing.model.InvoiceAndLetterOutputProperties;
import com.mckesson.eig.roi.billing.model.InvoiceHistory;
import com.mckesson.eig.roi.billing.model.InvoiceOrPrebillAndPreviewInfo;
import com.mckesson.eig.roi.billing.model.LetterInfo;
import com.mckesson.eig.roi.billing.model.PastInvoiceList;
import com.mckesson.eig.roi.billing.model.ReleaseAndPreviewInfo;
import com.mckesson.eig.roi.billing.model.ReleaseCore;
import com.mckesson.eig.roi.billing.model.ReleaseHistoryList;
import com.mckesson.eig.roi.billing.model.RequestCoreDeliveryCharges;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2021-09-21T19:01:26.518+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:eig.mckesson.com", name = "BillingCoreService")
//@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, ObjectFactory.class})
public interface BillingCoreService {

    @WebMethod(action = "urn:eig.mckesson.com/cancelInvoiceOrPrebillAndPreview")
    @RequestWrapper(localName = "cancelInvoiceOrPrebillAndPreview", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.CancelInvoiceOrPrebillAndPreview")
    @ResponseWrapper(localName = "cancelInvoiceOrPrebillAndPreviewResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.CancelInvoiceOrPrebillAndPreviewResponse")
    public void cancelInvoiceOrPrebillAndPreview(
        @WebParam(name = "requestCoreId", targetNamespace = "urn:eig.mckesson.com")
        long requestCoreId
    );

    @WebMethod(action = "urn:eig.mckesson.com/viewInvoice")
    @RequestWrapper(localName = "viewInvoice", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.ViewInvoice")
    @ResponseWrapper(localName = "viewInvoiceResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.ViewInvoiceResponse")
    @WebResult(name = "docInfo", targetNamespace = "urn:eig.mckesson.com")
    public DocInfo viewInvoice(
        @WebParam(name = "invoiceId", targetNamespace = "urn:eig.mckesson.com")
        long invoiceId,
        @WebParam(name = "docType", targetNamespace = "urn:eig.mckesson.com")
        String docType
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveChargeHistory")
    @RequestWrapper(localName = "retrieveChargeHistory", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.RetrieveChargeHistory")
    @ResponseWrapper(localName = "retrieveChargeHistoryResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.RetrieveChargeHistoryResponse")
    @WebResult(name = "chargeHistoryList", targetNamespace = "urn:eig.mckesson.com")
    public ChargeHistoryList retrieveChargeHistory(
        @WebParam(name = "requestId", targetNamespace = "urn:eig.mckesson.com")
        long requestId
    );

    @WebMethod(action = "urn:eig.mckesson.com/setDisplayBillingInfo")
    @RequestWrapper(localName = "setDisplayBillingInfo", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.SetDisplayBillingInfo")
    @ResponseWrapper(localName = "setDisplayBillingInfoResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.SetDisplayBillingInfoResponse")
    public void setDisplayBillingInfo(
        @WebParam(name = "requestId", targetNamespace = "urn:eig.mckesson.com")
        long requestId,
        @WebParam(name = "displayBillingInfo", targetNamespace = "urn:eig.mckesson.com")
        boolean displayBillingInfo
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveInvoiceSummaries")
    @RequestWrapper(localName = "retrieveInvoiceSummaries", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.RetrieveInvoiceSummaries")
    @ResponseWrapper(localName = "retrieveInvoiceSummariesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.RetrieveInvoiceSummariesResponse")
    @WebResult(name = "invoiceHistory", targetNamespace = "urn:eig.mckesson.com")
    public InvoiceHistory retrieveInvoiceSummaries(
        @WebParam(name = "requestCoreId", targetNamespace = "urn:eig.mckesson.com")
        long requestCoreId
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrievePastInvoices")
    @RequestWrapper(localName = "retrievePastInvoices", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.RetrievePastInvoices")
    @ResponseWrapper(localName = "retrievePastInvoicesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.RetrievePastInvoicesResponse")
    @WebResult(name = "PastInvoiceList", targetNamespace = "urn:eig.mckesson.com")
    public PastInvoiceList retrievePastInvoices(
        @WebParam(name = "requestId", targetNamespace = "urn:eig.mckesson.com")
        long requestId
    );

    @WebMethod(action = "urn:eig.mckesson.com/createReleaseAndPreviewInfo")
    @RequestWrapper(localName = "createReleaseAndPreviewInfo", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.CreateReleaseAndPreviewInfo")
    @ResponseWrapper(localName = "createReleaseAndPreviewInfoResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.CreateReleaseAndPreviewInfoResponse")
    @WebResult(name = "releaseAndPreviewInfo", targetNamespace = "urn:eig.mckesson.com")
    public ReleaseAndPreviewInfo createReleaseAndPreviewInfo(
        @WebParam(name = "releaseCore", targetNamespace = "urn:eig.mckesson.com")
        ReleaseCore releaseCore,
        @WebParam(name = "amtAppliedFlag", targetNamespace = "urn:eig.mckesson.com")
        boolean amtAppliedFlag,
        @WebParam(name = "appliedAmount", targetNamespace = "urn:eig.mckesson.com")
        double appliedAmount
    );

    @WebMethod(action = "urn:eig.mckesson.com/autoApplyToInvoice")
    @RequestWrapper(localName = "autoApplyToInvoice", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.AutoApplyToInvoice")
    @ResponseWrapper(localName = "autoApplyToInvoiceResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.AutoApplyToInvoiceResponse")
    public void autoApplyToInvoice(
        @WebParam(name = "requestId", targetNamespace = "urn:eig.mckesson.com")
        long requestId,
        @WebParam(name = "invoiceId", targetNamespace = "urn:eig.mckesson.com")
        long invoiceId
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateInvoiceOutputProperties")
    @RequestWrapper(localName = "updateInvoiceOutputProperties", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.UpdateInvoiceOutputProperties")
    @ResponseWrapper(localName = "updateInvoiceOutputPropertiesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.UpdateInvoiceOutputPropertiesResponse")
    public void updateInvoiceOutputProperties(
        @WebParam(name = "invoiceAndLetterOutputProperties", targetNamespace = "urn:eig.mckesson.com")
        InvoiceAndLetterOutputProperties invoiceAndLetterOutputProperties
    );

    @WebMethod(action = "urn:eig.mckesson.com/createLetterAndPreview")
    @RequestWrapper(localName = "createLetterAndPreview", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.CreateLetterAndPreview")
    @ResponseWrapper(localName = "createLetterAndPreviewResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.CreateLetterAndPreviewResponse")
    @WebResult(name = "docInfo", targetNamespace = "urn:eig.mckesson.com")
    public DocInfo createLetterAndPreview(
        @WebParam(name = "letterInfo", targetNamespace = "urn:eig.mckesson.com")
        LetterInfo letterInfo
    );

    @WebMethod(action = "urn:eig.mckesson.com/retrieveReleaseHistoryList")
    @RequestWrapper(localName = "retrieveReleaseHistoryList", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.RetrieveReleaseHistoryList")
    @ResponseWrapper(localName = "retrieveReleaseHistoryListResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.RetrieveReleaseHistoryListResponse")
    @WebResult(name = "releaseHistoryList", targetNamespace = "urn:eig.mckesson.com")
    public ReleaseHistoryList retrieveReleaseHistoryList(
        @WebParam(name = "releaseId", targetNamespace = "urn:eig.mckesson.com")
        long releaseId
    );

    @WebMethod(action = "urn:eig.mckesson.com/cancelRelease")
    @RequestWrapper(localName = "cancelRelease", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.CancelRelease")
    @ResponseWrapper(localName = "cancelReleaseResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.CancelReleaseResponse")
    public void cancelRelease(
        @WebParam(name = "releaseId", targetNamespace = "urn:eig.mckesson.com")
        long releaseId,
        @WebParam(name = "invoiceId", targetNamespace = "urn:eig.mckesson.com")
        long invoiceId
    );

    @WebMethod(action = "urn:eig.mckesson.com/updateInvoiceBalance")
    @RequestWrapper(localName = "updateInvoiceBalance", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.UpdateInvoiceBalance")
    @ResponseWrapper(localName = "updateInvoiceBalanceResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.UpdateInvoiceBalanceResponse")
    public void updateInvoiceBalance(
        @WebParam(name = "invoiceId", targetNamespace = "urn:eig.mckesson.com")
        long invoiceId,
        @WebParam(name = "invoiceBalance", targetNamespace = "urn:eig.mckesson.com")
        double invoiceBalance
    );

    @WebMethod(action = "urn:eig.mckesson.com/cancelCoverLetter")
    @RequestWrapper(localName = "cancelCoverLetter", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.CancelCoverLetter")
    @ResponseWrapper(localName = "cancelCoverLetterResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.CancelCoverLetterResponse")
    public void cancelCoverLetter(
        @WebParam(name = "requestId", targetNamespace = "urn:eig.mckesson.com")
        long requestId,
        @WebParam(name = "coverLetterId", targetNamespace = "urn:eig.mckesson.com")
        long coverLetterId
    );

    @WebMethod(action = "urn:eig.mckesson.com/createInvoiceOrPrebillAndPreview")
    @RequestWrapper(localName = "createInvoiceOrPrebillAndPreview", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsRequestWrapper.CreateInvoiceOrPrebillAndPreview")
    @ResponseWrapper(localName = "createInvoiceOrPrebillAndPreviewResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.billingCoreService.wsResponseWrapper.CreateInvoiceOrPrebillAndPreviewResponse")
    @WebResult(name = "docInfo", targetNamespace = "urn:eig.mckesson.com")
    public DocInfo createInvoiceOrPrebillAndPreview(
        @WebParam(name = "invoiceOrPrebillAndPreviewInfo", targetNamespace = "urn:eig.mckesson.com")
        InvoiceOrPrebillAndPreviewInfo invoiceOrPrebillAndPreviewInfo
    );

    List<RequestCoreDeliveryCharges> retrieveAllInvoicesByIds(
            List<Long> invoiceIds);

    String regenerateLetter(long id, String fileType, String type);

    List<Object[]> retrievePrebillReportDetailsWithRequestorName(
            String[] facList, String[] reqType, String reqName,
            String[] reqStatus, String fromDt, String toDt, String balance,
            String balanceCriterion, String resultType);

    List<Object[]> retrievePrebillReportDetailsWithoutRequestorName(
            String[] facList, String[] reqType, String[] reqStatus,
            String fromDt, String toDt, String balance, String balanceCriterion,
            String resultType);

    List<Object[]> retrievePostPaymentReportDetails(String[] facList,
            List<String> userName, String[] reqType, Date fromDt, Date toDt,
            String resultType);
}
