package com.mckesson.eig.roi.billing.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.mckesson.eig.roi.billing.model.InvoiceAndLetterInfo;
import com.mckesson.eig.roi.billing.model.OverDueDocInfoList;
import com.mckesson.eig.roi.billing.model.SearchPastDueInvoiceCriteria;
import com.mckesson.eig.roi.billing.model.SearchPastDueInvoiceResult;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2021-09-21T19:34:50.231+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:eig.mckesson.com", name = "OverdueInvoiceCoreService")
//@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, ObjectFactory.class})
public interface OverDueInvoiceCoreService {

    @WebMethod(action = "urn:eig.mckesson.com/regenerateInvoiceCoreAndLetter")
    @RequestWrapper(localName = "regenerateInvoiceCoreAndLetter", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.overdueInvoiceCoreService.wsRequestWrapper.RegenerateInvoiceCoreAndLetter")
    @ResponseWrapper(localName = "regenerateInvoiceCoreAndLetterResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.overdueInvoiceCoreService.wsResponseWrapper.RegenerateInvoiceCoreAndLetterResponse")
    @WebResult(name = "overDueDocInfoList", targetNamespace = "urn:eig.mckesson.com")
    public OverDueDocInfoList regenerateInvoiceCoreAndLetter(
        @WebParam(name = "InvoiceAndLetterInfo", targetNamespace = "urn:eig.mckesson.com")
        InvoiceAndLetterInfo invoiceAndLetterInfo,
        @WebParam(name = "forPreview", targetNamespace = "urn:eig.mckesson.com")
        boolean forPreview
    );

    @WebMethod(action = "urn:eig.mckesson.com/searchOverDueInvoices")
    @RequestWrapper(localName = "searchOverDueInvoices", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.overdueInvoiceCoreService.wsRequestWrapper.SearchOverDueInvoices")
    @ResponseWrapper(localName = "searchOverDueInvoicesResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.overdueInvoiceCoreService.wsResponseWrapper.SearchOverDueInvoicesResponse")
    @WebResult(name = "searchPastDueInvoiceResult", targetNamespace = "urn:eig.mckesson.com")
    public SearchPastDueInvoiceResult searchOverDueInvoices(
        @WebParam(name = "PastDueInvoiceCriteria", targetNamespace = "urn:eig.mckesson.com")
        SearchPastDueInvoiceCriteria pastDueInvoiceCriteria
    );
    
    /**
     * This method generates the requestor letter/ regenerated Invoice PDF file from the given Ids  
     * @param id
     * @param fileType
     * @param type
     * @return file path of the generated PDF File
     */
    String regenerateLetter(long id, String fileType, String type);
}
