//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace McK.EIG.ROI.Client.Web_References.ROIRequestWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ROIRequestSoapBinding", Namespace="urn:eig.mckesson.com")]
    public partial class RequestServiceWse : McK.EIG.ROI.Client.Base.Controller.CustomWebServicesClientProtocol //Microsoft.Web.Services3.WebServicesClientProtocol
    {
        
        private @long transactionIdField;
        
        private SecurityHeaderType securityField;
        
        private System.Threading.SendOrPostCallback createRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback searchRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback getEventHistoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveCommentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback addEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback retrieveAllEventTypesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRequestCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback getGeneratedPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAuditAndEventOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RequestServiceWse() {
            this.Url = global::McK.EIG.ROI.Client.Properties.Settings.Default.McK_EIG_ROI_Client_Web_References_ROIRequestWS_RequestService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public @long transactionId {
            get {
                return this.transactionIdField;
            }
            set {
                this.transactionIdField = value;
            }
        }
        
        public SecurityHeaderType Security {
            get {
                return this.securityField;
            }
            set {
                this.securityField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event createRequestCompletedEventHandler createRequestCompleted;
        
        /// <remarks/>
        public event retrieveRequestCompletedEventHandler retrieveRequestCompleted;
        
        /// <remarks/>
        public event updateRequestCompletedEventHandler updateRequestCompleted;
        
        /// <remarks/>
        public event deleteRequestCompletedEventHandler deleteRequestCompleted;
        
        /// <remarks/>
        public event searchRequestCompletedEventHandler searchRequestCompleted;
        
        /// <remarks/>
        public event getEventHistoryCompletedEventHandler getEventHistoryCompleted;
        
        /// <remarks/>
        public event retrieveCommentsCompletedEventHandler retrieveCommentsCompleted;
        
        /// <remarks/>
        public event addEventCompletedEventHandler addEventCompleted;
        
        /// <remarks/>
        public event retrieveAllEventTypesCompletedEventHandler retrieveAllEventTypesCompleted;
        
        /// <remarks/>
        public event getRequestCountCompletedEventHandler getRequestCountCompleted;
        
        /// <remarks/>
        public event getGeneratedPasswordCompletedEventHandler getGeneratedPasswordCompleted;
        
        /// <remarks/>
        public event addAuditAndEventCompletedEventHandler addAuditAndEventCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/createRequest", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void createRequest(ref Request request) {
            object[] results = this.Invoke("createRequest", new object[] {
                        request});
            request = ((Request)(results[0]));
        }
        
        /// <remarks/>
        public void createRequestAsync(Request request) {
            this.createRequestAsync(request, null);
        }
        
        /// <remarks/>
        public void createRequestAsync(Request request, object userState) {
            if ((this.createRequestOperationCompleted == null)) {
                this.createRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateRequestOperationCompleted);
            }
            this.InvokeAsync("createRequest", new object[] {
                        request}, this.createRequestOperationCompleted, userState);
        }
        
        private void OncreateRequestOperationCompleted(object arg) {
            if ((this.createRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.createRequestCompleted(this, new createRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/retrieveRequest", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("request")]
        public Request retrieveRequest(long id) {
            object[] results = this.Invoke("retrieveRequest", new object[] {
                        id});
            return ((Request)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveRequestAsync(long id) {
            this.retrieveRequestAsync(id, null);
        }
        
        /// <remarks/>
        public void retrieveRequestAsync(long id, object userState) {
            if ((this.retrieveRequestOperationCompleted == null)) {
                this.retrieveRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveRequestOperationCompleted);
            }
            this.InvokeAsync("retrieveRequest", new object[] {
                        id}, this.retrieveRequestOperationCompleted, userState);
        }
        
        private void OnretrieveRequestOperationCompleted(object arg) {
            if ((this.retrieveRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveRequestCompleted(this, new retrieveRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/updateRequest", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void updateRequest(ref Request request) {
            object[] results = this.Invoke("updateRequest", new object[] {
                        request});
            request = ((Request)(results[0]));
        }
        
        /// <remarks/>
        public void updateRequestAsync(Request request) {
            this.updateRequestAsync(request, null);
        }
        
        /// <remarks/>
        public void updateRequestAsync(Request request, object userState) {
            if ((this.updateRequestOperationCompleted == null)) {
                this.updateRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateRequestOperationCompleted);
            }
            this.InvokeAsync("updateRequest", new object[] {
                        request}, this.updateRequestOperationCompleted, userState);
        }
        
        private void OnupdateRequestOperationCompleted(object arg) {
            if ((this.updateRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateRequestCompleted(this, new updateRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/deleteRequest", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void deleteRequest(long requestId) {
            this.Invoke("deleteRequest", new object[] {
                        requestId});
        }
        
        /// <remarks/>
        public void deleteRequestAsync(long requestId) {
            this.deleteRequestAsync(requestId, null);
        }
        
        /// <remarks/>
        public void deleteRequestAsync(long requestId, object userState) {
            if ((this.deleteRequestOperationCompleted == null)) {
                this.deleteRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteRequestOperationCompleted);
            }
            this.InvokeAsync("deleteRequest", new object[] {
                        requestId}, this.deleteRequestOperationCompleted, userState);
        }
        
        private void OndeleteRequestOperationCompleted(object arg) {
            if ((this.deleteRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/searchRequest", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SearchRequestResult searchRequest(SearchLoVCriteria criteria, PaginationData paginationData) {
            object[] results = this.Invoke("searchRequest", new object[] {
                        criteria,
                        paginationData});
            return ((SearchRequestResult)(results[0]));
        }
        
        /// <remarks/>
        public void searchRequestAsync(SearchLoVCriteria criteria, PaginationData paginationData) {
            this.searchRequestAsync(criteria, paginationData, null);
        }
        
        /// <remarks/>
        public void searchRequestAsync(SearchLoVCriteria criteria, PaginationData paginationData, object userState) {
            if ((this.searchRequestOperationCompleted == null)) {
                this.searchRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchRequestOperationCompleted);
            }
            this.InvokeAsync("searchRequest", new object[] {
                        criteria,
                        paginationData}, this.searchRequestOperationCompleted, userState);
        }
        
        private void OnsearchRequestOperationCompleted(object arg) {
            if ((this.searchRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchRequestCompleted(this, new searchRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/getEventHistory", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestEvents")]
        public RequestEvents getEventHistory(long requestId) {
            object[] results = this.Invoke("getEventHistory", new object[] {
                        requestId});
            return ((RequestEvents)(results[0]));
        }
        
        /// <remarks/>
        public void getEventHistoryAsync(long requestId) {
            this.getEventHistoryAsync(requestId, null);
        }
        
        /// <remarks/>
        public void getEventHistoryAsync(long requestId, object userState) {
            if ((this.getEventHistoryOperationCompleted == null)) {
                this.getEventHistoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetEventHistoryOperationCompleted);
            }
            this.InvokeAsync("getEventHistory", new object[] {
                        requestId}, this.getEventHistoryOperationCompleted, userState);
        }
        
        private void OngetEventHistoryOperationCompleted(object arg) {
            if ((this.getEventHistoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getEventHistoryCompleted(this, new getEventHistoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/retrieveComments", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("comments")]
        public Comments retrieveComments(long requestId) {
            object[] results = this.Invoke("retrieveComments", new object[] {
                        requestId});
            return ((Comments)(results[0]));
        }
        
        /// <remarks/>
        public void retrieveCommentsAsync(long requestId) {
            this.retrieveCommentsAsync(requestId, null);
        }
        
        /// <remarks/>
        public void retrieveCommentsAsync(long requestId, object userState) {
            if ((this.retrieveCommentsOperationCompleted == null)) {
                this.retrieveCommentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveCommentsOperationCompleted);
            }
            this.InvokeAsync("retrieveComments", new object[] {
                        requestId}, this.retrieveCommentsOperationCompleted, userState);
        }
        
        private void OnretrieveCommentsOperationCompleted(object arg) {
            if ((this.retrieveCommentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveCommentsCompleted(this, new retrieveCommentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/addEvent", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addEvent(ref RequestEvent events) {
            object[] results = this.Invoke("addEvent", new object[] {
                        events});
            events = ((RequestEvent)(results[0]));
        }
        
        /// <remarks/>
        public void addEventAsync(RequestEvent events) {
            this.addEventAsync(events, null);
        }
        
        /// <remarks/>
        public void addEventAsync(RequestEvent events, object userState) {
            if ((this.addEventOperationCompleted == null)) {
                this.addEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddEventOperationCompleted);
            }
            this.InvokeAsync("addEvent", new object[] {
                        events}, this.addEventOperationCompleted, userState);
        }
        
        private void OnaddEventOperationCompleted(object arg) {
            if ((this.addEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addEventCompleted(this, new addEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/retrieveAllEventTypes", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("eventType")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("eventType", IsNullable=false)]
        public string[] retrieveAllEventTypes() {
            object[] results = this.Invoke("retrieveAllEventTypes", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void retrieveAllEventTypesAsync() {
            this.retrieveAllEventTypesAsync(null);
        }
        
        /// <remarks/>
        public void retrieveAllEventTypesAsync(object userState) {
            if ((this.retrieveAllEventTypesOperationCompleted == null)) {
                this.retrieveAllEventTypesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnretrieveAllEventTypesOperationCompleted);
            }
            this.InvokeAsync("retrieveAllEventTypes", new object[0], this.retrieveAllEventTypesOperationCompleted, userState);
        }
        
        private void OnretrieveAllEventTypesOperationCompleted(object arg) {
            if ((this.retrieveAllEventTypesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.retrieveAllEventTypesCompleted(this, new retrieveAllEventTypesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/getRequestCount", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long getRequestCount(SearchLoVCriteria criteria) {
            object[] results = this.Invoke("getRequestCount", new object[] {
                        criteria});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void getRequestCountAsync(SearchLoVCriteria criteria) {
            this.getRequestCountAsync(criteria, null);
        }
        
        /// <remarks/>
        public void getRequestCountAsync(SearchLoVCriteria criteria, object userState) {
            if ((this.getRequestCountOperationCompleted == null)) {
                this.getRequestCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRequestCountOperationCompleted);
            }
            this.InvokeAsync("getRequestCount", new object[] {
                        criteria}, this.getRequestCountOperationCompleted, userState);
        }
        
        private void OngetRequestCountOperationCompleted(object arg) {
            if ((this.getRequestCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRequestCountCompleted(this, new getRequestCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/getGeneratedPassword", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getGeneratedPassword() {
            object[] results = this.Invoke("getGeneratedPassword", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getGeneratedPasswordAsync() {
            this.getGeneratedPasswordAsync(null);
        }
        
        /// <remarks/>
        public void getGeneratedPasswordAsync(object userState) {
            if ((this.getGeneratedPasswordOperationCompleted == null)) {
                this.getGeneratedPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetGeneratedPasswordOperationCompleted);
            }
            this.InvokeAsync("getGeneratedPassword", new object[0], this.getGeneratedPasswordOperationCompleted, userState);
        }
        
        private void OngetGeneratedPasswordOperationCompleted(object arg) {
            if ((this.getGeneratedPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getGeneratedPasswordCompleted(this, new getGeneratedPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("transactionId")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:eig.mckesson.com/addAuditAndEvent", RequestNamespace="urn:eig.mckesson.com", ResponseNamespace="urn:eig.mckesson.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void addAuditAndEvent(AuditAndEventList auditAndEventList) {
            this.Invoke("addAuditAndEvent", new object[] {
                        auditAndEventList});
        }
        
        /// <remarks/>
        public void addAuditAndEventAsync(AuditAndEventList auditAndEventList) {
            this.addAuditAndEventAsync(auditAndEventList, null);
        }
        
        /// <remarks/>
        public void addAuditAndEventAsync(AuditAndEventList auditAndEventList, object userState) {
            if ((this.addAuditAndEventOperationCompleted == null)) {
                this.addAuditAndEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAuditAndEventOperationCompleted);
            }
            this.InvokeAsync("addAuditAndEvent", new object[] {
                        auditAndEventList}, this.addAuditAndEventOperationCompleted, userState);
        }
        
        private void OnaddAuditAndEventOperationCompleted(object arg) {
            if ((this.addAuditAndEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAuditAndEventCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2001/XMLSchema")]
    [System.Xml.Serialization.XmlRootAttribute("transactionId", Namespace="urn:eig.mckesson.com", IsNullable=false)]
    public partial class @long : System.Web.Services.Protocols.SoapHeader {
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    [System.Xml.Serialization.XmlRootAttribute("Security", Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "", IsNullable=false)]
    public partial class SecurityHeaderType : System.Web.Services.Protocols.SoapHeader {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class AuditEvent {
        
        private long eventIdField;
        
        private bool eventIdFieldSpecified;
        
        private long domainIdField;
        
        private bool domainIdFieldSpecified;
        
        private long componentIdField;
        
        private bool componentIdFieldSpecified;
        
        private long userIdField;
        
        private bool userIdFieldSpecified;
        
        private System.DateTime eventStartField;
        
        private bool eventStartFieldSpecified;
        
        private System.Nullable<System.DateTime> eventEndField;
        
        private bool eventEndFieldSpecified;
        
        private System.Nullable<long> eventStatusField;
        
        private bool eventStatusFieldSpecified;
        
        private string locationField;
        
        private System.Nullable<long> objectIdField;
        
        private bool objectIdFieldSpecified;
        
        private string commentField;
        
        private string workflowReasonField;
        
        private string actionCodeField;
        
        private string encounterField;
        
        private string facilityField;
        
        private string mrnField;
        
        /// <remarks/>
        public long eventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventIdSpecified {
            get {
                return this.eventIdFieldSpecified;
            }
            set {
                this.eventIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long domainId {
            get {
                return this.domainIdField;
            }
            set {
                this.domainIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool domainIdSpecified {
            get {
                return this.domainIdFieldSpecified;
            }
            set {
                this.domainIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long componentId {
            get {
                return this.componentIdField;
            }
            set {
                this.componentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool componentIdSpecified {
            get {
                return this.componentIdFieldSpecified;
            }
            set {
                this.componentIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime eventStart {
            get {
                return this.eventStartField;
            }
            set {
                this.eventStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventStartSpecified {
            get {
                return this.eventStartFieldSpecified;
            }
            set {
                this.eventStartFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> eventEnd {
            get {
                return this.eventEndField;
            }
            set {
                this.eventEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventEndSpecified {
            get {
                return this.eventEndFieldSpecified;
            }
            set {
                this.eventEndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> eventStatus {
            get {
                return this.eventStatusField;
            }
            set {
                this.eventStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool eventStatusSpecified {
            get {
                return this.eventStatusFieldSpecified;
            }
            set {
                this.eventStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> objectId {
            get {
                return this.objectIdField;
            }
            set {
                this.objectIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool objectIdSpecified {
            get {
                return this.objectIdFieldSpecified;
            }
            set {
                this.objectIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string workflowReason {
            get {
                return this.workflowReasonField;
            }
            set {
                this.workflowReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string actionCode {
            get {
                return this.actionCodeField;
            }
            set {
                this.actionCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string encounter {
            get {
                return this.encounterField;
            }
            set {
                this.encounterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string facility {
            get {
                return this.facilityField;
            }
            set {
                this.facilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mrn {
            get {
                return this.mrnField;
            }
            set {
                this.mrnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class AuditAndEventList {
        
        private RequestEvent[] eventsField;
        
        private AuditEvent[] auditEventField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("events")]
        public RequestEvent[] events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auditEvent")]
        public AuditEvent[] auditEvent {
            get {
                return this.auditEventField;
            }
            set {
                this.auditEventField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class RequestEvent {
        
        private long requestIdField;
        
        private bool requestIdFieldSpecified;
        
        private string nameField;
        
        private string typeField;
        
        private string descriptionField;
        
        private string originatorField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private bool modifiedDateFieldSpecified;
        
        /// <remarks/>
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestIdSpecified {
            get {
                return this.requestIdFieldSpecified;
            }
            set {
                this.requestIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedDateSpecified {
            get {
                return this.modifiedDateFieldSpecified;
            }
            set {
                this.modifiedDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Comment {
        
        private long requestIdField;
        
        private bool requestIdFieldSpecified;
        
        private string typeField;
        
        private string descriptionField;
        
        private string originatorField;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private bool createdDateFieldSpecified;
        
        /// <remarks/>
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestIdSpecified {
            get {
                return this.requestIdFieldSpecified;
            }
            set {
                this.requestIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdDateSpecified {
            get {
                return this.createdDateFieldSpecified;
            }
            set {
                this.createdDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Comments {
        
        private Comment[] commentField;
        
        private int commentsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("comment")]
        public Comment[] comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public int commentsCount {
            get {
                return this.commentsCountField;
            }
            set {
                this.commentsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class RequestEvents {
        
        private RequestEvent[] eventsField;
        
        private int eventsCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("events")]
        public RequestEvent[] events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
            }
        }
        
        /// <remarks/>
        public int eventsCount {
            get {
                return this.eventsCountField;
            }
            set {
                this.eventsCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class SearchRequestResult {
        
        private Request[] requestsField;
        
        private bool maxCountExceededField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("requests")]
        public Request[] requests {
            get {
                return this.requestsField;
            }
            set {
                this.requestsField = value;
            }
        }
        
        /// <remarks/>
        public bool maxCountExceeded {
            get {
                return this.maxCountExceededField;
            }
            set {
                this.maxCountExceededField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Request {
        
        private long idField;
        
        private string detailsField;
        
        private int statusField;
        
        private string statusReasonField;
        
        private string updatedByField;
        
        private System.Nullable<System.DateTime> modifiedDateField;
        
        private bool modifiedDateFieldSpecified;
        
        private System.Nullable<System.DateTime> createdDateField;
        
        private bool createdDateFieldSpecified;
        
        private int recordVersionField;
        
        private ROILoV[] lovField;
        
        private Release[] releasesField;
        
        private Transaction[] transactionField;
        
        private bool deleteReleaseField;
        
        private long releaseIdField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string statusReason {
            get {
                return this.statusReasonField;
            }
            set {
                this.statusReasonField = value;
            }
        }
        
        /// <remarks/>
        public string updatedBy {
            get {
                return this.updatedByField;
            }
            set {
                this.updatedByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modifiedDate {
            get {
                return this.modifiedDateField;
            }
            set {
                this.modifiedDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modifiedDateSpecified {
            get {
                return this.modifiedDateFieldSpecified;
            }
            set {
                this.modifiedDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createdDateSpecified {
            get {
                return this.createdDateFieldSpecified;
            }
            set {
                this.createdDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int recordVersion {
            get {
                return this.recordVersionField;
            }
            set {
                this.recordVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lov")]
        public ROILoV[] lov {
            get {
                return this.lovField;
            }
            set {
                this.lovField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("releases")]
        public Release[] releases {
            get {
                return this.releasesField;
            }
            set {
                this.releasesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transaction")]
        public Transaction[] transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
            }
        }
        
        /// <remarks/>
        public bool deleteRelease {
            get {
                return this.deleteReleaseField;
            }
            set {
                this.deleteReleaseField = value;
            }
        }
        
        /// <remarks/>
        public long releaseId {
            get {
                return this.releaseIdField;
            }
            set {
                this.releaseIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class ROILoV {
        
        private long idField;
        
        private string domainTypeField;
        
        private string domainSourceField;
        
        private string keyField;
        
        private string valueField;
        
        private long childField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string domainType {
            get {
                return this.domainTypeField;
            }
            set {
                this.domainTypeField = value;
            }
        }
        
        /// <remarks/>
        public string domainSource {
            get {
                return this.domainSourceField;
            }
            set {
                this.domainSourceField = value;
            }
        }
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public long child {
            get {
                return this.childField;
            }
            set {
                this.childField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Release {
        
        private long idField;
        
        private System.DateTime releaseDateField;
        
        private long userIdField;
        
        private string userNameField;
        
        private string detailsField;
        
        private int recordVersionField;
        
        private long requestIdField;
        
        private bool requestIdFieldSpecified;
        
        private Item itemField;
        
        private ROILoV[] releasedSupplementalDocsField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime releaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                this.releaseDateField = value;
            }
        }
        
        /// <remarks/>
        public long userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public int recordVersion {
            get {
                return this.recordVersionField;
            }
            set {
                this.recordVersionField = value;
            }
        }
        
        /// <remarks/>
        public long requestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestIdSpecified {
            get {
                return this.requestIdFieldSpecified;
            }
            set {
                this.requestIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Item item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("releasedSupplementalDocs", IsNullable=true)]
        public ROILoV[] releasedSupplementalDocs {
            get {
                return this.releasedSupplementalDocsField;
            }
            set {
                this.releasedSupplementalDocsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Item {
        
        private string typeField;
        
        private attributesMap[] attributesField;
        
        private Item[] childItemField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes")]
        public attributesMap[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childItem")]
        public Item[] childItem {
            get {
                return this.childItemField;
            }
            set {
                this.childItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class attributesMap {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class Transaction {
        
        private string typeField;
        
        private string descriptionField;
        
        private string amountField;
        
        private string reasonNameField;
        
        private bool isDebitField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string reasonName {
            get {
                return this.reasonNameField;
            }
            set {
                this.reasonNameField = value;
            }
        }
        
        /// <remarks/>
        public bool isDebit {
            get {
                return this.isDebitField;
            }
            set {
                this.isDebitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class PaginationData {
        
        private int startIndexField;
        
        private int countField;
        
        private bool isDescField;
        
        private string domainTypeField;
        
        private string sortByField;
        
        /// <remarks/>
        public int startIndex {
            get {
                return this.startIndexField;
            }
            set {
                this.startIndexField = value;
            }
        }
        
        /// <remarks/>
        public int count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public bool isDesc {
            get {
                return this.isDescField;
            }
            set {
                this.isDescField = value;
            }
        }
        
        /// <remarks/>
        public string domainType {
            get {
                return this.domainTypeField;
            }
            set {
                this.domainTypeField = value;
            }
        }
        
        /// <remarks/>
        public string sortBy {
            get {
                return this.sortByField;
            }
            set {
                this.sortByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class SearchLov {
        
        private string domainTypeField;
        
        private string domainSourceField;
        
        private string keyField;
        
        private string conditionField;
        
        private string dataTypeField;
        
        private string valueField;
        
        private string valueToField;
        
        /// <remarks/>
        public string domainType {
            get {
                return this.domainTypeField;
            }
            set {
                this.domainTypeField = value;
            }
        }
        
        /// <remarks/>
        public string domainSource {
            get {
                return this.domainSourceField;
            }
            set {
                this.domainSourceField = value;
            }
        }
        
        /// <remarks/>
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string dataType {
            get {
                return this.dataTypeField;
            }
            set {
                this.dataTypeField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string valueTo {
            get {
                return this.valueToField;
            }
            set {
                this.valueToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:eig.mckesson.com")]
    public partial class SearchLoVCriteria {
        
        private int maxCountField;
        
        private SearchLov[] searchlovsField;
        
        /// <remarks/>
        public int maxCount {
            get {
                return this.maxCountField;
            }
            set {
                this.maxCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("searchlovs")]
        public SearchLov[] searchlovs {
            get {
                return this.searchlovsField;
            }
            set {
                this.searchlovsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void createRequestCompletedEventHandler(object sender, createRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class createRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal createRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Request request {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Request)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void retrieveRequestCompletedEventHandler(object sender, retrieveRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Request Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Request)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void updateRequestCompletedEventHandler(object sender, updateRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Request request {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Request)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void deleteRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void searchRequestCompletedEventHandler(object sender, searchRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SearchRequestResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SearchRequestResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getEventHistoryCompletedEventHandler(object sender, getEventHistoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getEventHistoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getEventHistoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RequestEvents Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestEvents)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void retrieveCommentsCompletedEventHandler(object sender, retrieveCommentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveCommentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveCommentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Comments Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Comments)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void addEventCompletedEventHandler(object sender, addEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RequestEvent events {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RequestEvent)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void retrieveAllEventTypesCompletedEventHandler(object sender, retrieveAllEventTypesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class retrieveAllEventTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal retrieveAllEventTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getRequestCountCompletedEventHandler(object sender, getRequestCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRequestCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRequestCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void getGeneratedPasswordCompletedEventHandler(object sender, getGeneratedPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getGeneratedPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getGeneratedPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void addAuditAndEventCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591