--- 
name: JBoss Application Server 5.1.0.GA Binary
platform_id: all
platform_version: all
distribution_file_uuid_string: openlogic-jboss-5.1.0.GA-all-bin-1
platform_vendor: all
version_visibility: public
description: JBoss Application Server 5.1.0.GA Binary
platform_arch: all
distribution_file_uuid: c870fa1cb712ad9673f9fdbd05d404361467a461cec960da4eec6298db521be7
distribution_version: 1
distribution_flavor: ""
distribution_raw_file: 5.1.0.GA/jboss-5.1.0.GA.zip
package_version: 5.1.0.GA
package_id: jboss
release_date: "2009-05-27"
distribution_notes: ""
distribution_type: bin
