; Section ROI Server
[ROI]
protocol = http
ip = emiqc2133
port = 18080
WINDSS_DATABASE=emiqc2133
WINDSS_USER=epr
WINDSS_PSWD=7EA98F6460434AB6

; Section PORTAL Server
[PORTAL]
protocol = http
ip = EMIqc2133
port = 18080

