/**
 *
 */
package com.mckesson.eig.roi.config.util.api;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Properties;
import java.util.Set;

import javax.swing.JOptionPane;

/**
 * @author Shah Mohamed.N
 * @date   Dev 22, 2010
 * @since  HPF 15.1 [ROI]; Dev 22, 2010
 */
public class AutoConfigurator {

	/** To hold the global properties **/
	private static Properties _properties;

	private static String configXmlLoc = System.getProperty("user.home")
											+ File.separator + "roi.auto.config.xml";

	/**
	 * This method is to return the global properties.
	 * @return props
	 */
	public static Properties getProps() {

		if (null == _properties) {
			_properties = new Properties();
		}
		return _properties;
	}

	/**
	 * This method is used to add new properties.
	 * @param props
	 */
	public static void addProperties(Map<String, String> props, TabSource source) {

		Set<Entry<String, String>> entries =  props.entrySet();

		for (Entry<String, String> entry : entries) {
			addProperty(source.toString() + "_" + entry.getKey(), entry.getValue());
		}
	}

	/**
	 * This method is used to add new property with key and value.
	 * @param key
	 * @param value
	 */
	public static void addProperty(String key, String value) {
		getProps().setProperty(key, value);
	}

	/**
	 * This method is to export an XML and store it in the
	 * default location mentioned. The Global properties is the
	 * input for generating the XML.
	 */
	public static void exportXML() {

		File file = new File(configXmlLoc);
		try {

			/** Creating the FileOutput Stream **/
			FileOutputStream fos = new FileOutputStream(file);

			/** Store the properties in to XML**/
			getProps().storeToXML(fos, "DO NOT EDIT THIS FILE COZ IT IS USED BY CONFIG UTILITY");

			fos.close();
		} catch (FileNotFoundException e) {
			showErrMsg("Unable to export XML : " + e.getMessage());
		} catch (IOException e) {
			showErrMsg(e.getMessage());
		}
	}

	/**
	 * This method is used to import the XML properties in to Global properties.
	 */
	public static void importXML() {

		getProps().clear();

		File file = new File(configXmlLoc);
		try {

			FileInputStream fis = new FileInputStream(file);
			getProps().loadFromXML(fis);
			AutoConfigurator.addProperty("isUpdated", "false");

		} catch (Exception e) {
			showErrMsg("Unable to import XML : " + e.getMessage());
		}
	}

	/**
	 * This method is used to return the config params for the keys specified.
	 * @param keys
	 * @return config params.
	 */
	public static Map<String, String> getConfigParams(TabSource source) {

		Set<Entry<Object,Object>> props = getProps().entrySet();

		HashMap<String, String> params = new HashMap<String, String>();

		String key = "";
		for ( Entry<Object, Object> entry : props) {

			key = (String) entry.getKey();
			if (!key.startsWith(source.toString())) {
				continue;
			}

			params.put(getSuppressedKey(key, source.toString()), (String) entry.getValue());
		}

		return params;
	}

	private static String getSuppressedKey(String key, String source) {
			return key.substring(source.length() + 1);
	}

	private static void showErrMsg(String message) {
		JOptionPane.showMessageDialog(null, message, "Error", JOptionPane.ERROR_MESSAGE);
	}

	public static boolean isConfigExists() {
		try {
			return (new File(configXmlLoc)).exists();
		} catch (Throwable e) {
			// ignore
			return false;
		}
	}
}
