/*
BEGIN-COPYRIGHT-COMMENT Do not remove or modify this line!

* Copyright © 2012 McKesson Corporation and/or one of its subsidiaries. All Rights Reserved.
* Use of this software and related documentation is governed by a license agreement.
* This material contains confidential, proprietary and trade secret information of
* McKesson Information Solutions and is protected under United States
* and international copyright and other intellectual property laws.
* Use, disclosure, reproduction, modification, distribution, or storage
* in a retrieval system in any form or by any means is prohibited without the
* prior express written permission of McKesson Information Solutions.

END-COPYRIGHT-COMMENT  Do not remove or modify this line!
*/

package com.mckesson.eig.roi.base.api;

import com.mckesson.eig.utility.exception.ClientErrorCodes;


/**
 * @author ganeshramr
 * @date   Jul 7, 2009
 * @since  HPF 13.1 [ROI]; Apr 24, 2008
 */
public enum ROIClientErrorCodes {

    // Common error codes
    ROI_APPLICATION_ERROR("ROI.0.0.00"),

    //Seed data validation
    SEED_DATA_IS_BEING_DELETED("ROI.0.0.01"),
    //Error codes for File Transfer
    FILE_TRANSFER_HELPER_NOT_DEFINED("ROI.0.0.02"),
    //Error codes for reading properties from roi.properties
    READ_PROPERTIES_FAILED("ROI.0.0.03"),
    EPN_PREFIX_DIFFERS("ROI.0.0.04"),
    DATABASE_OPERATION_FAILED("ROI.0.1.01"),

    ADDRESS1_LENGTH_EXCEEDS_LIMIT("ROI.0.0.05"),
    ADDRESS2_LENGTH_EXCEEDS_LIMIT("ROI.0.0.06"),
    ADDRESS3_LENGTH_EXCEEDS_LIMIT("ROI.0.0.07"),
    CITY_LENGTH_EXCEEDS_LIMIT("ROI.0.0.08"),
    STATE_LENGTH_EXCEEDS_LIMIT("ROI.0.0.09"),
    POSTALCODE_LENGTH_EXCEEDS_LIMIT("ROI.0.0.10"),
    INVALID_MAIN_ADDRESS("ROI.0.0.19"),
    INVALID_CITY_NAME("ROI.0.0.20"),
    INVALID_ZIP_CODE("ROI.0.0.21"),
    INVALID_STATE_NAME("ROI.0.0.22"),

    //Common error for spl characters
    INVALID_SPECIAL_CHARACTERS_FOUND("ROI.0.0.23"),
    COULD_NOT_GET_USER("ROI.0.0.24"),
    USER_ID_CANNOT_BE_EMPTY("ROI.0.0.25"),

    DATA_ACCESS_EXCEPTION("ROI.0.0.17"),
    RETRIEVE_FREE_FORM_FACILITIES_OPERATION_FAILED("ROI.0.0.18"),

   //Media Type Error codes
    MEDIA_TYPE_NAME_IS_NOT_UNIQUE("A01") ,
    MEDIA_TYPE_SEED_DATA_NAME_IS_BEING_EDITED("ROI.1.3.00"),
    MEDIA_TYPE_NAME_IS_BLANK("ROI.1.3.01"),
    MEDIA_TYPE_SEED_DATA_IS_BEING_DELETED("ROI.1.3.02"),
    MEDIA_TYPE_ASSOCIATED_WITH_BILLING_TIER("ROI.1.3.03"),
    MEDIA_TYPE_OPERATION_FAILED("ROI.1.3.04"),
    MEDIA_TYPE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.3.05"),
    MEDIA_TYPE_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.3.06"),
    MEDIA_TYPE_NAME_CONTAINS_INVALID_CHAR("ROI.1.3.07"),
    MEDIA_TYPE_DESC_CONTAINS_INVALID_CHAR("ROI.1.3.08"),

    //Fee type error codes
    FEE_TYPE_NAME_IS_NOT_UNIQUE("A05"),
    FEE_TYPE_NAME_IS_BLANK("ROI.1.4.01"),
    FEE_TYPE_ASSOCIATED_WITH_BILLING_TEMPLATE("ROI.1.4.02"),
    FEE_TYPE_PROCESS_FAILED("ROI.1.4.03"),
    FEE_TYPE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.4.04"),
    FEE_TYPE_INVALID_CHARGE_AMOUNT("ROI.1.4.05"),
    FEE_TYPE_NAME_CONTAINS_INVALID_CHAR("ROI.1.4.06"),
    FEE_TYPE_DESC_CONTAINS_INVALID_CHAR("ROI.1.4.07"),
    FEE_TYPE_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.4.08"),
    FEE_TYPE_AMOUNT_CONTAINS_INVALID_CHAR("ROI.1.4.09"),
    FEE_TYPE_AMOUNT_LENGTH_EXCEEDS_LIMIT("ROI.1.4.10"),
    RETRIEVE_FEE_TYPE_BY_REQUESTOR_TYPE_FAILED("ROI.1.4.11"),
    //Delivery Method error codes
    DELIVERY_METHOD_NAME_IS_NOT_UNIQUE("A08"),
    DELIVERY_METHOD_NAME_IS_BLANK("ROI.1.2.01"),
    DELIVERY_METHOD_OPERATION_FAILED("ROI.1.2.02"),
    DELIVERY_METHOD_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.2.04"),
    DELIVERY_METHOD_URL_LENGTH_EXCEEDS_LIMIT("ROI.1.2.05"),
    DELIVERY_METHOD_NAME_CONTAINS_INVALID_CHAR("ROI.1.2.06"),
    DELIVERY_METHOD_DESC_CONTAINS_INVALID_CHAR("ROI.1.2.07"),
    DELIVERY_METHOD_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.2.08"),
    DELIVERY_METHOD_URL_CONTAINS_INVALID_CHAR("ROI.1.2.09"),
   //Payment Method error codes
    PAYMENT_METHOD_NAME_IS_NOT_UNIQUE("A09"),
    PAYMENT_METHOD_NAME_IS_BLANK("ROI.1.5.01"),
    PAYMENT_METHOD_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.5.02"),
    PAYMENT_METHOD_OPERATION_FAILED("ROI.1.5.04"),
    PAYMENT_METHOD_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.5.05"),
    PAYMENT_METHOD_NAME_CONTAINS_INVALID_CHAR("ROI.1.5.06"),
    PAYMENT_METHOD_DESC_CONTAINS_INVALID_CHAR("ROI.1.5.07"),
    //Weight error codes
    WEIGHT_INVALID_PAGE_VALUE("ROI.1.7.00"),
    WEIGHT_METHOD_OPERATION_FAILED("ROI.1.7.01"),

    //invoice Due error codes
    INVOICE_INVALID_DUE_DAYS_VALUE("ROI.1.14.00"),
    INVOICE_DUE_DAYS_METHOD_OPERATION_FAILED("ROI.1.14.01"),
    INVALID_INVOICE_DATE_FORMAT("ROI.1.14.02"),

    //Billing Template error codes
    BILLING_TEMPLATE_NAME_IS_NOT_UNIQUE("A06"),
    BILLING_TEMPLATE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.6.00"),
    BILLING_TEMPLATE_NAME_IS_BLANK("ROI.1.6.01"),
    BILLING_TEMPLATE_IS_ASSOCIATED_WITH_REQUESTOR_TYPE("ROI.1.6.02"),
    BILLING_TEMPLATE_PROCESS_FAILED("ROI.1.6.03"),
    BILLING_TEMPLATE_NAME_CONTAINS_INVALID_CHAR("ROI.1.6.04"),
    //BillingTier
    BILLNG_TIER_NAME_IS_NOT_UNIQUE("A02"),
    BILLING_TIER_NAME_IS_BLANK("ROI.1.1.01"),
    BILLING_TIER_DOESNOT_HAVE_MEDIA_TYPE_ASSOCIATION("ROI.1.1.02"),
    BILLING_TIER_ASSOCIATED_WITH_NON_HPF("ROI.1.1.03"),
    BILLING_TIER_ATLEAST_HAVE_ONE_PAGE_LEVEL_TIER("ROI.1.1.04"),
    BILLING_TIER_ASSOCIATED_TO_REQUESTOR_TYPE_DELETED("ROI.1.1.06"),
    BILLING_TIER_SEED_DATA_NAME_IS_BEING_EDITED("ROI.1.1.07"),
    BILLING_TIER_SEED_DATA_MEDIA_TYPE_IS_BEING_EDITED("ROI.1.1.08"),
    BILLING_TIER_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.1.09"),
    BILLING_TIER_AMOUNTS_SHOULD_BE_POSITIVE("ROI.1.1.10"),
    BILLING_TIER_OPERATION_FAILED("ROI.1.1.11"),
    INVALID_BASE_CHARGE_AMOUNT("ROI.1.1.12"),
    INVALID_PAGE_CHARGE_AMOUNT("ROI.1.1.13"),
    INVALID_DEFAULT_PAGE_CHARGE_AMOUNT("ROI.1.1.14"),
    INVALID_PAGE_NUMBER("ROI.1.1.15"),
    BILLING_TIER_NAME_CONTAINS_INVALID_CHAR("ROI.1.1.16"),
    BILLING_TIER_DESC_CONTAINS_INVALID_CHAR("ROI.1.1.17"),
    BILLING_TIER_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.1.18"),
    //ROI.1.1.16 to ROI.1.1.18 are being used by client for local errors
    ELECTRONIC_BILLING_TIER_ASSOCIATED_TO_REQUESTOR_TYPE_CANNOT_BE_MODIFIED("ROI.1.1.19"),
    BILLING_TIER_CHARGE_IS_BLANK("ROI.1.1.20"),
    BILLING_TIER_CHARGE_CONTAINS_INVALID_CHAR("ROI.1.1.21"),
    BILLING_TIER_CHARGE_LENGTH_EXCEEDS_LIMIT("ROI.1.1.22"),

    //Reason error codes
    ADJUSTMENT_REASON_NAME_IS_NOT_UNIQUE("A010"),
    STATUS_REASON_NAME_IS_NOT_UNIQUE("A011"),
    STATUS_REASON_DISPLAY_TEXT_IS_NOT_UNIQUE("A012"),
    REQUEST_REASON_NAME_IS_NOT_UNIQUE("A013"),
    REASON_NAME_IS_BLANK("ROI.1.8.00"),
    REASON_DISPLAY_TEXT_IS_BLANK("ROI.1.8.01"),
    REASON_DISPLAY_TEXT_IS_NOT_UNIQUE("ROI.1.8.02"),
    REQUEST_REASON_ATTRIBUTE_IS_BLANK("ROI.1.8.03"),
    STATUS_REASON_STATUS_FIELD_IS_BLANK("ROI.1.8.04"),
    REASON_NAME_LENGTH_EXCEEDS("ROI.1.8.05"),
    REASON_DISPLAY_TEXT_LENGTH_EXCEEDS("ROI.1.8.06"),
    REASON_OPERATION_FAILED("ROI.1.8.07"),
    REASON_NAME_CONTAINS_INVALID_CHAR("ROI.1.8.08"),
    REASON_DISPLAY_TEXT_CONTAINS_INVALID_CHAR("ROI.1.8.10"),

    //RequestorType error codes
    REQUESTOR_TYPE_NAME_IS_NOT_UNIQUE("A07"),
    REQUESTOR_TYPE_NAME_IS_BLANK("ROI.1.9.01"),
    REQUESTOR_TYPE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.9.02"),
    REQUESTOR_TYPE_MUST_HAVE_ONE_HPF_BILLING_TIER("ROI.1.9.03"),
    REQUESTOR_TYPE_MUST_HAVE_ONE_RECORD_VIEW("ROI.1.9.04"),
    REQUESTOR_TYPE_SEED_DATA_IS_MODIFIED("ROI.1.9.05"),
    REQUESTOR_TYPE_SEED_DATA_IS_DELETED("ROI.1.9.06"),
    REQUESTOR_TYPE_BTIER_NAME_IS_NOT_ELECTRONIC("ROI.1.9.07"),
    REQUESTOR_TYPE_OPERATION_FAILED("ROI.1.9.08"),
    REQUESTOR_TYPE_BILLING_TEMPLATE_HAVE_MORE_THAN_ONE_DEFAULT("ROI.1.9.09"),
    REQUESTOR_TYPE_ASSOCIATED_WITH_REQUESTOR_IS_DELETED("ROI.1.9.11"),
    REQUESTOR_TYPE_MUST_HAVE_ONE_NON_HPF_BILLING_TIER("ROI.1.9.12"),
    INVALID_BILLING_TIER_ASSOCIATION("ROI.1.9.13"),
    REQUESTOR_TYPE_MUST_HAVE_HPF_AND_NON_HPF_BILLING_TIER("ROI.1.9.14"),
    INVALID_BILLING_TEMPLATE_ASSOCIATION("ROI.1.9.15"),

    //For Record View
    RECORD_VIEW_OPERATION_FAILED("ROI.1.9.10"),

    //For Disclosure Document
    DISCLOSURE_DOCUMENT_OPERATION_FAILED("ROI.1.10.00"),

    //For LetterTemplate
    LETTER_TEMPLATE_NAME_IS_NOT_UNIQUE("A014"),
    LETTER_TEMPLATE_LETTER_TYPE_OTHER_CHOOSE_DEFAULT("ROI.1.11.00"),
    LETTER_TEMPLATE_NAME_IS_BLANK("ROI.1.11.01"),
    LETTER_TEMPLATE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.11.02"),
    LETTER_TEMPLATE_UPLOAD_FILENAME_LENGTH_EXCEEDS_LIMIT("ROI.1.11.03"),
    LETTER_TEMPLATE_PROCESS_FAILED("ROI.1.11.04"),
    LETTER_TEMPLATE_HAS_NO_ASSOCIATED_DOCUMENT("ROI.1.11.05"),
    LETTER_TEMPLATE_INVALID_FILE_FORMAT("ROI.1.11.06"),
    LETTER_TEMPLATE_PARSING_FAILED("ROI.1.11.07"),
    LETTER_TEMPLATE_NAME_CONTAINS_INVALID_CHAR("ROI.1.11.08"),
    LETTER_TEMPLATE_DESC_CONTAINS_INVALID_CHAR("ROI.1.11.09"),
    LETTER_TEMPLATE_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.11.10"),
    INVALID_LETTER_TEMPLATE_TYPE("ROI.1.11.16"),
	LETTER_TEMPLATE_DOCUMENT_LENGTH_EXCEEDS_LIMIT("ROI.1.11.17"),
	
    //Attachment Location
    ATTACHMENT_OPERATION_FAILED("ROI.1.13.00"),
    INVALID_ATTACHMENT_LOCATION("ROI.1.13.01"),
    ATTACHMENT_LOCATION_NULL("ROI.1.13.02"),
    INSUFICIENT_PERMISION_ON_ATTACHMENT_FOLDER("ROI.1.13.03"),
    DATABASE_ATTACHMENT_CONFIG_MISSING("ROI.1.13.04"),
    FILE_OPERATION_FAILED("ROI.1.13.05"),
    TEMP_DIRECTORY_CONFIG_MISSING("ROI.1.13.06"),

    //SalesTax Per Facility
    FACILITY_CODE_IS_BLANK("ROI.1.15.00"),
    FACILITY_CODE_CONTAINS_INVALID_CHAR("ROI.1.15.01"),
    FACILITY_CODE_LENGTH_EXCEEDS_LIMIT("ROI.1.15.02"),
    FACILITY_DESC_CONTAINS_INVALID_CHAR("ROI.1.15.03"),
    FACILITY_DESC_LENGTH_EXCEEDS_LIMIT("ROI.1.15.04"),
    SALESTAX_PERCENTAGE_IS_BLANK("ROI.1.15.05"),
    SALESTAX_PERCENTAGE_CONTAINS_INVALID_CHAR("ROI.1.15.06"),
    SALESTAX_PERCENTAGE_LENGTH_EXCEEDS_LIMIT("ROI.1.15.07"),
    SALESTAX_OPERATION_FAILED("ROI.1.15.08"),
    SALES_TAX_FACILITY_CODE_IS_NOT_UNIQUE("ROI.1.15.09"),
    USER_HAS_NO_SECURITY_RIGHTS("ROI.1.15.14"),

    //For FindRequestor
    REQUESTOR_NAME_SHOULD_HAVE_ATLEAST_TWO_CHARACTERS("ROI.2.1.00"),
    REQUESTOR_EPN_SHOULD_HAVE_ATLEAST_THREE_CHARACTERS("ROI.2.1.01"),
    REQUESTOR_SSN_SHOULD_HAVE_ATLEAST_THREE_CHARACTERS("ROI.2.1.02"),
    REQUESTOR_PATIENT_MRN_ATLEAST_THREE_CHARACTERS("ROI.2.1.33"),
    REQUESTOR_NAME_IS_MANDATORY("ROI.2.1.04"),
    REQUESTOR_TYPE_IS_MANDATORY("ROI.2.1.05"),
    REQUESTOR_ASSOCIATED_WITH_REQUEST_IS_DELETED("ROI.2.1.07"),
    REQUESTOR_SEARCH_OPERATION_FAILED("ROI.2.1.08"),
    REQUESTOR_INVALID_SEARCH_CRITERIA("ROI.2.1.09"),
    REQUESTOR_OPERATION_FAILED("ROI.2.1.10"),

    REQUESTOR_NAME_LENGTH_EXCEEDS_LIMIT("ROI.2.1.11"),
    REQUESTOR_PATIENT_EPN_LENGTH_EXCEEDS_LIMIT("ROI.2.1.12"),
    REQUESTOR_PATIENT_SSN_LENGTH_EXCEEDS_LIMIT("ROI.2.1.13"),
    REQUESTOR_PATIENT_DOB_CONTAINS_FUTURE_DATE("ROI.2.1.14"),
    REQUESTOR_CONTACT_NAME_LENGTH_EXCEEDS_LIMIT("ROI.2.1.15"),
    REQUESTOR_TYPE_NAME_CONTAINS_INVALID_CHAR("ROI.2.1.16"),
    REQUESTOR_NAME_CONTAINS_INVALID_CHAR("ROI.2.1.17"),
    INVALID_PATIENT_EPN("ROI.2.1.18"),
    INVALID_PATIENT_SSN("ROI.2.1.19"),
    INVALID_HOME_PHONE("ROI.2.1.20"),
    PHONE_LENGTH_EXCEEDS_LIMIT("ROI.2.1.21"),
    INVALID_WORK_PHONE("ROI.2.1.22"),
    INVALID_CELL_PHONE("ROI.2.1.23"),
    INVALID_EMAIL("ROI.2.1.24"),
    REQUESTOR_EMAIL_LENGTH_EXCEEDS_LIMIT("ROI.2.1.25"),
    INVALID_FAX("ROI.2.1.26"),
    REQUESTOR_FAX_LENGTH_EXCEEDS_LIMIT("ROI.2.1.27"),
    INVALID_CONTACT_NAME("ROI.2.1.28"),
    INVALID_CONTACT_PHONE_NUMBER("ROI.2.1.30"),
    CONTACT_PHONE_LENGTH_EXCEEDS_LIMIT("ROI.2.1.31"),
    CONTACT_EMAIL_LENGTH_EXCEEDS_LIMIT("ROI.2.1.32"),
    //Client Error Codes
    SYSTEM_COULD_NOT_LOG_YOU_ON(ClientErrorCodes.SYSTEM_COULD_NOT_LOG_YOU_ON),
    OPTIMISTIC_LOCKING_COLLISION(ClientErrorCodes.OPTIMISTIC_LOCKING_COLLISION),
    DATA_INTEGRITY_VIOLATION(ClientErrorCodes.DATA_INTEGRITY_VIOLATION),
    INVALID_ID(ClientErrorCodes.INVALID_ID),
    PATIENT_INUSE("ROI.3.0.00"),
    REQUESTOR_INUSE("ROI.2.0.00"),

    //ForNonHpfDocuments
    NON_HPF_DOCUMENT_PROCESS_FAILED("ROI.3.3.06"),

    //for record view details
    RETRIEVE_RECORD_VIEW_DETAILS_OPERATION_FAILED("ROI.3.3.07"),

    //Find Patient Requestor matching
    EMPTY_MATCH_CRITERIA("ROI.6.0.00"),
    EMPTY_MATCH_CRITERIA_LIST("ROI.6.0.01"),
    MATCH_CRITERIA_LIST_INVALID("ROI.6.0.02"),
    MATCH_CRITERIA_LIST_CONTAINS_EMPTY_MATCH_CRITERIA("ROI.6.0.03"),
    MATCHING_OPERATION_FAILED("ROI.6.0.04"),

    //Request
    REQUEST_MODEL_IS_EMPTY("ROI.4.0.00"),
    REQUEST_DETAILS_IS_NULL("ROI.4.0.17"),
    CAN_NOT_DELETE_HAS_RELEASE("ROI.4.0.18"),
    REQUEST_OPERATION_FAILED("ROI.4.1.05"),
    REQUEST_LOV_CREATE_OPERATION_FAILED("ROI.4.0.19"),
    //Request Search
    SEARCH_REQUEST_OPERATION_FAILED("ROI.4.0.10"),
    INVALID_PAGINATION_DATA("ROI.4.0.12"),
    GET_REQUEST_COUNT_OPERATION_FAILED("ROI.4.0.16"),

    // Adjustment and payment
    INVOICE_CHARGELIST_IS_NULL("ROI.4.0.20"),
    INVOICE_CHARGELIST_CONTAINS_INVLAID_ID("ROI.4.0.21"),
    UPDATE_ADJUSTMENT_PAYMENT_OPERATION_FAILED("ROI.4.0.26"),

    //Request Event
    REQUEST_EVENT_OPERATION_FAILED("ROI.5.0.01"),
    INVALID_REQUEST_ID("ROI.5.0.02"),
    EMPTY_REQUEST_EVENT_DESCRIPTION("ROI.5.0.03"),

    //Release History
    RELEASE_HISTORY_RETRIEVAL_FAILED("ROI.5.1.01"),

    //DocumentType
    AUTHORIZATION_DOC_TYPE_HAVE_MORE_THAN_ONE("ROI.1.10.01"),
    DESIGNATION_FOR_DOCUMENT_TYPE_IS_NULL("ROI.1.10.02"),

    //configureNote
    NOTE_NAME_IS_NOT_UNIQUE("ROI.1.12.00"),
    NOTE_NAME_IS_NULL("ROI.1.12.01"),
    ADMINLOV_OPERATION_FAILED("ROI.1.12.02"),
    NOTE_DISPLAY_TEXT_IS_NULL("ROI.1.12.03"),
    NOTE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.1.12.04"),
    NOTE_DISPLAY_TEXT_LENGTH_EXCEEDS_LIMIT("ROI.1.12.05"),
    NOTE_NAME_CONTAINS_INVALID_CHAR("ROI.1.12.06"),
    NOTE_DISPLAY_TEXT_CONTAINS_INVALID_CHAR("ROI.1.12.07"),
    NOTE_OPERATION_FAILED("ROI.1.12.08"),
    //Billing & Shipping
    INVALID_RELEASE_DETAILS("ROI.7.0.00"),
    INVALID_RELEASE_ITEMS("ROI.7.0.01"),
    INVALID_RELEASE_ID("ROI.7.0.02"),
    RELEASED_REQUEST_CANNOT_BE_DELETED("ROI.7.0.03"),
    RELEASE_OPERATION_FAILED("ROI.7.0.04"),
    INVALID_ID_OR_HAS_NO_RELEASE("ROI.7.0.07"),
    UNABLE_TO_PARSE_RELEASE_INFO_XML("ROI.7.0.08"),
    REQUEST_IS_ALREADY_RELEASED_CANT_PRE_BILL("ROI.7.0.09"),
    LETTER_TEMPLATE_ID_EQUAL_TO_ZERO("ROI.7.0.10"),
    INVALID_RELEASE("ROI.7.0.11"),
    UNABLE_TO_BUILD_PDF_TEMPLATE_DATA("ROI.7.0.12"),
    UNABLE_TO_GENERATE_PDF("ROI.7.0.13"),
    GENERATE_LETTER_OPERATION_FAILED("ROI.7.0.14"),

    UNABLE_TO_BUILD_RTF_TEMPLATE_DATA("ROI.7.0.15"),
    UNABLE_TO_GENERATE_RTF("ROI.7.0.16"),
    UNABLE_TO_CONVERT_TO_PDF("ROI.7.0.17"),

    UNABLE_TO_CONCATENATE_PDF("ROI.7.0.18"),
    UNABLE_TO_ENCRYPT_PDF("ROI.7.0.19"),

    INVOICE_CREATION_FAILED("ROI.7.0.21"),
    PREBILL_CREATION_FAILED("ROI.7.0.22"),
    LETTER_CREATION_FAILED("ROI.7.0.23"),
    UNABLE_TO_INSTANTIATE_RTF_DATA_BUILDER("ROI.7.0.24"),
    UNABLE_TO_MARSHALL_OBJECT("ROI.7.0.25"),
    UNABLE_TO_UNMARSHALL_XML("ROI.7.0.26"),
    UNABLE_TO_GENERATE_ODT("ROI.7.0.26"),
    UNABLE_TO_GENERATE_DOCX("ROI.7.0.26"),

    //ROISupplemental
    ROI_SUPPLEMENTAL_CANNOT_BE_NULL("ROI.3.1.11"),
    ROI_SUPPLEMENTAL_DETAILS_SHOULD_NOT_BE_NULL("ROI.3.1.12"),
    ROI_SUPPLEMENTAL_HAS_ASSOCIATION_WITH_REQUEST("ROI.3.1.13"),
    ROILOV_CANNOT_BE_NULL("ROI.3.1.14"),
    SEARCH_CRITERIA_CANNOT_BE_NULL("ROI.3.1.01"),
    ROI_SUPPLEMENTAL_OPERATION_FAILED("ROI.3.1.03"),
    ROI_ALREADY_RELEASED_ATTACHMENT("ROI.3.1.24"),
    ROI_ALREADY_RELEASED_DOCUMENT("ROI.3.1.23"),

    //SupplementalSearchCriteria
    SUPPLEMENTAL_SEARCH_CRITERIA_CAN_NOT_BE_NULL("ROI.3.1.16"),

    CCD_CCR_INVALID_FILE_FORMAT("ROI.7.0.25"),
    CCD_CCR_UNABLE_TO_CONVERT_PDF("ROI.7.0.26"),
    CCD_UNABLE_TO_GET_XSLT("ROI.7.0.27"),
    CCR_UNABLE_TO_GET_XSLT("ROI.7.0.28"),
    CCD_CCR_INVALID_PAGE_COUNT("ROI.7.0.29"),

     //External Sources
    CCD_CCR_EXTERNALSOURCES_RETRIEVAL("ROI.7.0.31"),
    CCD_CCR_UPDATE_PROVIDER("ROI.7.0.32"),
    CCD_CCR_UPDATE_PROVIDERCONFIG("ROI.7.0.33"),
    CCD_CCR_RETRIEVECCD("ROI.7.0.34"),
    CCD_CCR_TESTCONFIGURATION("ROI.7.0.35"),
    CCD_CCR_GETEXTERNALSOURCENAMEFORFACILITY("ROI.7.0.36"),
    CCD_CCR_CONNECTIONFAILED("ROI.7.0.37"),

    CCD_CCR_PROVIDERNAME("ROI.7.0.39"),
    CCD_CCR_PROVIDERSOURCENAME("ROI.7.0.40"),
    CCD_CCR_PROVIDERDESCRIPTION("ROI.7.0.41"),
    CCD_CCR_PROVIDERCONFIG("ROI.7.0.42"),
    CCD_CCR_PROVIDERNOTEXISTS("ROI.7.0.43"),
    CCD_CCR_PROVIDERCONFIGNOTREQUIRED("ROI.7.0.44"),
    CCD_CCR_SOURCEEXISTS("ROI.7.0.45"),

    CCD_CCR_CREATEOUTPUTSTREAM("ROI.7.0.46"),
    CCD_CCR_RETRIEVECCD_CLINICAL_REPORT("ROI.7.0.47"),
    CCD_CCR_RETRIEVECCD_CLINICAL_ERROR("ROI.7.0.48"),
    CCD_CCR_RETRIEVECCD_CLINICAL_TIMEOUT("ROI.7.0.49"),
    CCD_CCR_SOURCEMAPPINGS("ROI.7.0.50"),

    //Turn Around Time-Configure Days
    CONFIGURE_DAYS_RETRIEVE_WEEKENDDAYS("ROI.8.0.1"),
    CONFIGURE_DAYS_RETRIEVE_CONFIGURED_DAYS("ROI.8.0.2"),
    CONFIGURE_DAYS_CREATE_OR_UPDATE_DAYSTATUS("ROI.8.0.3"),
    CONFIGURE_GETDAYS_OBJECT("ROI.8.0.4"),

    //For MU DOC TYPE
    RETRIEVAL_MUDOCTYPES("ROI.9.0.1"),

    //REPORT GENERATION FOR MU
    MU_REPORT_GENERATION("ROI.9.0.2"),

    //MU CREATE ROI OUTBOUND
    MU_CREATEROIOUTBOUND("ROI.9.0.3"),
    MU_CREATEROIOUTBOUND_BULK_INSERT("ROI.9.0.5"),


    //MU UPDATE ROI OUTBOUND
    MU_UPDATEROIOUTBOUND("ROI.9.0.6"),
    
    //For SOGI
    RETRIEVAL_GENDER_DETAILS("ROI.9.0.7"),


    //Past Due Invoice Generation
    FACILITY_CODE_IS_NULL("ROI.8.0.01"),
    OVERDUE_DAYS_IS_INVALID("ROI.8.0.02"),
    OVERDUE_DAYS_FROM_IS_GREATER_THAN_TO("ROI.8.0.03"),
    REQUESTOR_TYPE_IS_NULL("ROI.8.0.04"),
    SEARCH_PASTDUE_INVOICE_OPERATION_FAILED("ROI.8.0.05"),
    REGENERATION_OPERATION_FAILED("ROI.8.0.06"),
    REQUESTOR_INVOICES_IS_BLANK("ROI.8.0.07"),
    OVERDUE_RESTRICTION_IS_BLANK("ROI.8.0.08"),

    INVALID_SEARCH_CRITERIA("ROI.8.0.09"),
    INVOICE_ID_IS_BLANK("ROI.8.0.10"),
    INVOICE_TEMPLATE_ID_IS_NULL("ROI.8.0.11"),
    INVOICE_OVERDUE_DAYS_IS_BLANK("ROI.8.0.12"),
    INVALID_INVOICE_ID_OR_NOT_INVOICED("ROI.8.0.13"),
    INVALID_ITEM_XML_TO_BUILD_TEMPLATE_DATA("ROI.8.0.14"),
    INVALID_CURRENCY_TYPE("ROI.8.0.15"),
    INVALID_REQUESTOR_ID("ROI.8.0.16"),
    UPDATE_REQUESTOR_LETTER_OPERATION_FAILED("ROI.8.0.17"),
    INVALID_PROPERTIES("ROI.8.0.18"),
    INVALID_TEMPLATE_ID("ROI.8.0.19"),
    REGENERATED_INVOICE_IS_NULL("ROI.8.0.20"),
    INVOICES_AND_LETTER_INFO_IS_NULL("ROI.8.0.21"),
    REQUEST_DETAILS_PARSING_FAILED("ROI.8.0.22"),
    TEMPLATE_ID_IS_BLANK("ROI.8.0.23"),
    QUEUE_PASSWORD_LENGTH_EXCEEDS_LIMIT("ROI.8.0.24"),
    REQUEST_PASSWORD_LENGTH_EXCEEDS_LIMIT("ROI.8.0.25"),
    INVALID_DATE_RANGE("ROI.8.0.26"),
    INVALID_STATEMENT_CRITERIA("ROI.8.0.27"),
    RETRIEVE_REQUESTOR_OPERATION_FAILED("ROI.8.0.28"),

    //Past Invoice Listing
    UNABLE_TO_RETRIEVE_PAST_INVOICE("ROI.9.0.1"),

    //Output Server Properties
    OUTPUT_SERVER_HOSTNAME_EMPTY("OU_001"),
    OUTPUT_SERVER_INVALID_HOSTNAME("OU_002"),
    OUTPUT_SERVER_PORT_EMPTY("OU_003"),
    OUTPUT_SERVER_INVALID_PORT("OU_004"),
    OUTPUT_SERVER_PROTOCOL_EMPTY("OU_005"),
    OUTPUT_SERVER_INVALID_PROTOCOL("OU_006"),
    OUTPUT_SERVER_HOSTNAME_LENGTH_EXCEEDS_LIMIT("OU_007"),
    OUTPUT_SERVER_PORT_LENGTH_EXCEEDS_LIMIT("OU_008"),
    OUTPUT_SERVER_PROTOCOL_LENGTH_EXCEEDS_LIMIT("OU_009"),

    //ROI Attachment Infos
    ROI_ATTACHMENT_MRN_CANNOT_BE_NULL("ROI.7.0.30"),
    ROI_ATTACHMENT_FACILITY_CANNOT_BE_NULL("ROI.7.0.31"),
    ROI_ATTACHMENT_ENCOUNTER_CANNOT_BE_NULL("ROI.7.0.32"),
    RERTRIEVE_ATTACHMENT_INFO_FAILED("ROI.7.0.33"),
    REQUEST_PATIENT_IS_EMPTY("ROI.7.0.34"),
    ROI_ATTACHMENT_SEQ_IS_EMPTY("ROI.7.0.35"),
    DELETE_ROI_ATTACHMENT_FROM_DATABASE_FAILED("ROI.7.0.36"),
    INVALID_ROI_ATTACHMENT("ROI.7.0.37"),
    DELETE_ROI_ATTACHMENT_FAILED("ROI.7.0.38"),
    DELETE_ROI_ATTACHMENT_LOV_FAILED("ROI.7.0.39"),
    DELETE_ROI_ATTACHMENT_ENTRY_FAILED("ROI.7.0.40"),
    RERTRIEVE_ATTACHMENT_FAILED("ROI.7.0.41"),
    DELETE_ROI_ATTACHMENT_SUPPLLEMENTAL_FAILED("ROI.7.0.42"),
    REQUEST_CORE_ID_IS_EMPTY("ROI.7.0.43"),

    // Default details for Request Core details
    UNABLE_TO_LOAD_DEFAULT_VALUES("ROI.10.0.00"),
    UNABLE_TO_INVOKE_METHOD("ROI.10.0.01"),
    UNABLE_TO_GET_DATABASE_CONNECTION("ROI.10.0.02"),
    UNABLE_TO_CREATE_PREPARE_STATEMENT("ROI.10.0.03"),
    FAILED_TO_ADD_BATCH("ROI.10.0.04"),
    FAILED_TO_ATLEAST_ONE_EXECUTE_BATCH("ROI.10.0.05"),
    FAILED_TO_EXECUTE_BATCH("ROI.10.0.06"),
    INVALID_PREPARED_STATEMENT("ROI.10.0.07"),
    PREPARED_STATEMENT_CONTAINS_UNEXECUTED_QUERY("ROI.10.0.08"),

    // CRUD requestcore details
    REQUESTOR_MODEL_IS_EMPTY("ROI.10.1.00"),
    CREATE_REQUEST_CORE_OPERATION_FAILED("ROI.10.1.01"),
    UPDATE_REQUEST_CORE_OPERATION_FAILED("ROI.10.1.02"),
    RETRIEVE_REQUEST_CORE_OPERATION_FAILED("ROI.10.1.03"),

    // CRUD requestCore patient
    CREATE_REQUEST_CORE_PATIENT_OPERATION_FAILED("ROI.10.2.00"),
    DELETE_REQUEST_CORE_OPERATION_FAILED("ROI.10.2.01"),
    UNABLE_TO_CREATE_REQUEST_PATIENT("ROI.10.2.02"),
    UNABLE_TO_CREATE_REQUEST_PATIENT_ENCOUNTER("ROI.10.2.03"),
    UNABLE_TO_CREATE_REQUEST_PATIENT_DOCUMENT("ROI.10.2.04"),
    UNABLE_TO_CREATE_REQUEST_PATIENT_VERSION("ROI.10.2.05"),
    UNABLE_TO_CREATE_REQUEST_PATIENT_PAGE("ROI.10.2.06"),
    RETRIEVE_REQUEST_PATIENT_FAILED("ROI.10.2.07"),
    INVALID_PATIENT_ID("ROI.10.2.08"),
    INVALID_ENCOUNTER_ID("ROI.10.2.09"),
    INVALID_PATIENT_DETAILS("ROI.10.2.10"),
    UPDATE_REQUEST_PATIENT_FAILED("ROI.10.2.11"),
    DELETE_REQUEST_PATIENT_FAILED("ROI.10.2.18"),
    INSERT_OPERATION_FAILED("ROI.10.2.19"),
    RETRIEVE_OPERATION_FAILED("ROI.10.2.20"),
    UPDATE_OPERATION_FAILED("ROI.10.2.21"),
    DELETE_OPERATION_FAILED("ROI.10.2.22"),

    MANDATORY_FIELD_IS_BLANK("ROI.10.2.23"),
    FIELD_LENGTH_EXCEED_LIMIT("ROI.10.2.24"),

    REQUEST_STATUS_IS_BLANK("ROI.10.2.25"),
    REQUEST_STATUS_LENGTH_EXCEEDS_LIMIT("ROI.10.2.26"),
    STATUS_REASON_LENGTH_EXCEEDS_LIMIT("ROI.10.2.27"),
    REQUEST_PASSWORD_IS_BLANK("ROI.10.2.28"),
    REQUEST_REASON_IS_BLANK("ROI.10.2.29"),
    REQUEST_REASON_LENGTH_EXCEEDS_LIMIT("ROI.10.2.30"),
    RECEIPT_DATE_IS_BLANK("ROI.10.2.31"),
    RECEIPT_DATE_LENGTH_EXCEEDS_LIMIT("ROI.10.2.32"),
    REQUEST_REASON_ATTRIBUTE_LENGTH_EXCEEDS_LIMIT("ROI.10.2.33"),

    // CRUD requestor details
    CREATE_REQUEST_REQUESTOR_OPERATION_FAILED("ROI.10.3.01"),
    UPDATE_REQUEST_REQUESTOR_OPERATION_FAILED("ROI.10.3.02"),
    RETRIEVE_REQUEST_REQUESTOR_OPERATION_FAILED("ROI.10.3.03"),

    REQUESTOR_TYPE_IS_BLANK("ROI.10.3.04"),
    REQUESTOR_TYPE_LENGTH_EXCEEDS_LIMIT("ROI.10.3.05"),
    REQUESTOR_WORK_PHONE_LENGTH_EXCEEDS_LIMIT("ROI.10.3.06"),
    REQUESTOR_HOME_PHONE_LENGTH_EXCEEDS_LIMIT("ROI.10.3.07"),
    REQUESTOR_CONTACT_PHONE_LENGTH_EXCEEDS_LIMIT("ROI.10.3.08"),
    REQUESTOR_FIRST_NAME_LENGTH_EXCEEDS_LIMIT("ROI.10.3.09"),
    REQUESTOR_LAST_NAME_LENGTH_EXCEEDS_LIMIT("ROI.10.3.10"),
    REQUESTOR_MIDDLE_NAME_LENGTH_EXCEEDS_LIMIT("ROI.10.3.11"),
    REQUESTOR_FAX_NUMBER_LENGTH_EXCEEDS_LIMIT("ROI.10.3.12"),
    REQUESTOR_CELL_PHONE_LENGTH_EXCEEDS_LIMIT("ROI.10.3.13"),
    REQUESTOR_SUFFIX_LENGTH_EXCEEDS_LIMIT("ROI.10.3.14"),

    // Request DSR fields
    REQUEST_CONTAINS_INVALID_DOCUMENTS("ROI.10.4.1"),
    REQUEST_CONTAINS_INVALID_ATTACHMENTS("ROI.10.4.2"),

    // RequestCore Search fields
    INVALID_REQUEST_SEARCH_CRITERIA("ROI.10.5.1"),
    REQUESTSEARCH_CANNOT_BE_PERFORMED_WITH_GIVEN_CRITERIA("ROI.10.5.2"),


    //RequestCoreCharges CRUD Operations
    REQUEST_CORE_CHARGES_OPERATION_FAILED("ROI.10.9.01"),

    CREATE_REQUEST_CORE_DELIVERY_RELEASE_OPERATION_FAILED("ROI.10.9.02"),
    RETRIEVE_REQUEST_CORE_DELIVERY_OPERATION_FAILED("ROI.10.9.03"),
    REQUEST_BILLING_PAYMENT_OPERATION_FAILED("ROI.10.9.04"),
    CANCEL_REQUEST_CORE_DELIVERY_OPERATION_FAILED("ROI.10.9.05"),
    CREATE_REQUEST_CORE_DELIVERY_INVOICE_OPERATION_FAILED("ROI.10.9.06"),
    VIEW_INVOICE_OPERATION_FAILED("ROI.10.9.07"),
    CREATE_REGENERATE_INVOICE_OPERATION_FAILED("ROI.10.9.08"),
    RETRIEVE_INVOICE_HISTROY_OPERATION_FAILED("ROI.10.9.09"),
    RETRIEVE_INVOICE_OPERATION_FAILED("ROI.10.9.10"),
    INVOICE_DETAILS_SHOULD_NOT_BE_EMPTY("ROI.10.9.11"),
    FAILED_TO_UPDATE_REQUESTCORE_CHARGES_AS_RELEASED("ROI.10.9.12"),
    INVALID_REQUESTCORE_CHARGES("ROI.10.9.12"),
    CREATE_AUDIT_AND_REQUEST_EVENT_FAILED("ROI.10.9.13"),
    FAILED_TO_MARK_REQUEST_AS_DRAFT_RELEASE("ROI.10.9.14"),

    RETRIEVE_DOCUMENT_CHARGES_BY_BILLING_TIER_FAILED("ROI.10.9.15"),
    INVALID_INVOICE_ID("ROI.10.9.16"),
    INVALID_LETTER_ID("ROI.10.9.17"),

    //OverDueInvoice core
    REGENERATE_OVERDUE_INVOICE_TEMPLATE_ISEMPTY("ROI.10.6.01"),
    GENERATE_REQUESTOR_LETTER_FAILED("ROI.10.6.02"),

    INVALID_COVER_LETTER_ID("ROI.10.6.03"),
    FAILED_TO_CREATE_COVER_LETTER("ROI.10.6.04"),
    FAILED_TO_CREATE_COVER_LETTER_PATIENTS("ROI.10.6.05"),
    FAILED_TO_RETRIEVE_COVER_LETTER("ROI.10.6.06"),
    INVALID_COVER_LETTER("ROI.10.6.07"),
    INVALID_INVOICE("ROI.10.6.08"),

    //Country - Zip code services
    COUNTRY_CODE_CONFIG_UPDATE_OPERATION_FAILED("ROI.10.7.01"),
    COUNTRY_CODE_CONFIG_RETRIEVE_OPERATION_FAILED("ROI.10.7.02"),
    BILLING_CONFIGURATIONS_RETRIEVE_OPERATION_FAILED("ROI.10.7.03"),

    // freeform facility
    CREATE_FREEFORM_FACILITY_FAILED("ROI.10.8.01"),
    RETRIEVE_FREEFORM_FACILITY_FAILED("ROI.10.8.02"),

    //Journal Error code
    FAILED_TO_INSERT_JOURNAL_ENTRIES("ROI.10.12.01"),

    // ROI - Financial enhancement
    // CRUD Requestor Payment
    CREATE_REQUESTOR_PAYMENT("ROI.11.1.01"),
    UPDATE_REQUESTOR_PAYMENT("ROI.11.1.02"),
    REQUESTOR_PAYMENT_IS_NULL("ROI.11.1.03"),
    INVALID_REQUESTOR_PAYMENT_ID("ROI.11.1.04"),
    FAILED_TO_RETRIEVE_REQUEST_INVOICES("ROI.11.1.05"),
    RETRIEVE_UNAPPLIED_ADJUSTMENT("ROI.11.1.06"),
    RETRIEVE_REQUESTOR_HISTORY_OPERATION_FAILED("ROI.11.1.07"),
    VIEW_REQUESTOR_HISTORY_OPERATION_FAILED("ROI.11.1.08"),
    RETRIEVE_UNAPPLIED_AMOUNT_DETAILS("ROI.11.1.09"),
    INVALID_REQUESTOR_ADJUSTMENT_ID("ROI.11.1.10"),

    UNABLE_TO_RETRIEVE_REQUESTOR_ADJUSTMENT("ROI.11.2.01"),
    UNABLE_TO_SAVE_ADJUSTMENT("ROI.11.2.02"),
    CREATE_REQUESTOR_STATEMENT_FAILED("ROI.11.2.03"),
    GENERATE_REQUESTOR_STATEMENT_OPERATION_FAILED("ROI.11.2.04"),
    CREATE_REQUESTOR_REFUND_OPERTARION_FAILED("ROI.11.2.05"),
    INVALID_REFUND_DETAILS("ROI.11.2.06"),
    INVALID_REFUND_AMOUNT("ROI.11.2.07"),
    VIEW_REFUND_OPERATION_FAILED("ROI.11.2.08"),
    DELETE_REQUESTOR_PAYMENT_OPERATION_FAILED("ROI.11.2.09"),
    DELETE_REQUESTOR_ADJUSTMENT_OPERATION_FAILED("ROI.11.2.10"),

    ACCESS_TO_SHARE_DIRECTORY_DENIED("ROI.12.1.01"),
    SHARE_DIRECTORY_DOES_NOT_EXIST("ROI.12.1.02"),
    FAILED_TO_CREATE_AUTO_APPLY_TO_INVOICE("ROI.12.1.03"),
    FAILED_TO_UPDATE_INVOICE_BALANCE("ROI.12.1.04"),

// MPF Core server
    MPF_CORE_ADDRESS_NOT_CONFIGURED("ROI.13.1.01"),
    
    // Output service error
    SUBMIT_JOB_FAILED("ROI.14.1.01"),
    GET_SERVICE_PROPERTIES("ROI.14.1.02"),
    QUERY_OUTPUT_JOB("ROI.14.1.03"),
    GET_DESTINATIONS("ROI.14.1.04"),
    GET_DESTINATIONS_TYPE_INFO("ROI.14.1.05"),
    
    //Invalid input from Client
    INVALID_INPUT("ROI.15.1.01"),
    
    // Unbillable Request Flag Update
    UNABLE_TO_RETRIEVE_UNBILLABLE_REQUEST_FLAG("ROI.16.1.01"),
    UNABLE_TO_UPDATE_UNBILLABLE_REQUEST_FLAG("ROI.16.1.02");
    
    private final  String _errorCode;

    private ROIClientErrorCodes(String code) { _errorCode = code; }

    @Override
    public String toString() { return _errorCode; }
}
