package com.mckesson.eig.roi.hpf.service;


import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2021-09-21T20:05:33.796+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "urn:eig.mckesson.com", name = "SecurityLogoffService")
//@XmlSeeAlso({org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_secext_1_0.ObjectFactory.class, org.w3._2000._09.xmldsig_.ObjectFactory.class, org.oasis_open.docs.wss._2004._01.oasis_200401_wss_wssecurity_utility_1_0.ObjectFactory.class, ObjectFactory.class})
public interface SecurityLogoffService {

    /**
     * Used for user logoff
     */
    @WebMethod(action = "urn:eig.mckesson.com/logoff")
    @RequestWrapper(localName = "logoff", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.securityLogoffService.wsRequestWrapper.Logoff")
    @ResponseWrapper(localName = "logoffResponse", targetNamespace = "urn:eig.mckesson.com", className = "com.mckesson.eig.roi.cxfWrapperClasses.securityLogoffService.wsResponseWrapper.LogoffResponse")
    public void logoff();
}
